/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.olbaid.binance.service.model.ApiV3AccountCommissionGet200ResponseDiscount;
import com.olbaid.binance.service.model.ApiV3AccountCommissionGet200ResponseStandardCommission;
import com.olbaid.binance.service.model.ApiV3AccountCommissionGet200ResponseTaxCommission;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ApiV3AccountCommissionGet200Response
 */
@JsonPropertyOrder({
  ApiV3AccountCommissionGet200Response.JSON_PROPERTY_SYMBOL,
  ApiV3AccountCommissionGet200Response.JSON_PROPERTY_STANDARD_COMMISSION,
  ApiV3AccountCommissionGet200Response.JSON_PROPERTY_TAX_COMMISSION,
  ApiV3AccountCommissionGet200Response.JSON_PROPERTY_DISCOUNT
})
@JsonTypeName("_api_v3_account_commission_get_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ApiV3AccountCommissionGet200Response {
  public static final String JSON_PROPERTY_SYMBOL = "symbol";
  private String symbol;

  public static final String JSON_PROPERTY_STANDARD_COMMISSION = "standardCommission";
  private ApiV3AccountCommissionGet200ResponseStandardCommission standardCommission;

  public static final String JSON_PROPERTY_TAX_COMMISSION = "taxCommission";
  private ApiV3AccountCommissionGet200ResponseTaxCommission taxCommission;

  public static final String JSON_PROPERTY_DISCOUNT = "discount";
  private ApiV3AccountCommissionGet200ResponseDiscount discount;

  public ApiV3AccountCommissionGet200Response() {
  }

  public ApiV3AccountCommissionGet200Response symbol(String symbol) {
    
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "BTCUSDT", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSymbol() {
    return symbol;
  }


  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }


  public ApiV3AccountCommissionGet200Response standardCommission(ApiV3AccountCommissionGet200ResponseStandardCommission standardCommission) {
    
    this.standardCommission = standardCommission;
    return this;
  }

   /**
   * Get standardCommission
   * @return standardCommission
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_STANDARD_COMMISSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ApiV3AccountCommissionGet200ResponseStandardCommission getStandardCommission() {
    return standardCommission;
  }


  @JsonProperty(JSON_PROPERTY_STANDARD_COMMISSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStandardCommission(ApiV3AccountCommissionGet200ResponseStandardCommission standardCommission) {
    this.standardCommission = standardCommission;
  }


  public ApiV3AccountCommissionGet200Response taxCommission(ApiV3AccountCommissionGet200ResponseTaxCommission taxCommission) {
    
    this.taxCommission = taxCommission;
    return this;
  }

   /**
   * Get taxCommission
   * @return taxCommission
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TAX_COMMISSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ApiV3AccountCommissionGet200ResponseTaxCommission getTaxCommission() {
    return taxCommission;
  }


  @JsonProperty(JSON_PROPERTY_TAX_COMMISSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTaxCommission(ApiV3AccountCommissionGet200ResponseTaxCommission taxCommission) {
    this.taxCommission = taxCommission;
  }


  public ApiV3AccountCommissionGet200Response discount(ApiV3AccountCommissionGet200ResponseDiscount discount) {
    
    this.discount = discount;
    return this;
  }

   /**
   * Get discount
   * @return discount
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DISCOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ApiV3AccountCommissionGet200ResponseDiscount getDiscount() {
    return discount;
  }


  @JsonProperty(JSON_PROPERTY_DISCOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDiscount(ApiV3AccountCommissionGet200ResponseDiscount discount) {
    this.discount = discount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiV3AccountCommissionGet200Response apiV3AccountCommissionGet200Response = (ApiV3AccountCommissionGet200Response) o;
    return Objects.equals(this.symbol, apiV3AccountCommissionGet200Response.symbol) &&
        Objects.equals(this.standardCommission, apiV3AccountCommissionGet200Response.standardCommission) &&
        Objects.equals(this.taxCommission, apiV3AccountCommissionGet200Response.taxCommission) &&
        Objects.equals(this.discount, apiV3AccountCommissionGet200Response.discount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, standardCommission, taxCommission, discount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiV3AccountCommissionGet200Response {\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    standardCommission: ").append(toIndentedString(standardCommission)).append("\n");
    sb.append("    taxCommission: ").append(toIndentedString(taxCommission)).append("\n");
    sb.append("    discount: ").append(toIndentedString(discount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

