/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * OrderDetails
 */
@JsonPropertyOrder({
  OrderDetails.JSON_PROPERTY_SYMBOL,
  OrderDetails.JSON_PROPERTY_ORDER_ID,
  OrderDetails.JSON_PROPERTY_ORDER_LIST_ID,
  OrderDetails.JSON_PROPERTY_CLIENT_ORDER_ID,
  OrderDetails.JSON_PROPERTY_PRICE,
  OrderDetails.JSON_PROPERTY_ORIG_QTY,
  OrderDetails.JSON_PROPERTY_EXECUTED_QTY,
  OrderDetails.JSON_PROPERTY_CUMMULATIVE_QUOTE_QTY,
  OrderDetails.JSON_PROPERTY_STATUS,
  OrderDetails.JSON_PROPERTY_TIME_IN_FORCE,
  OrderDetails.JSON_PROPERTY_TYPE,
  OrderDetails.JSON_PROPERTY_SIDE,
  OrderDetails.JSON_PROPERTY_STOP_PRICE,
  OrderDetails.JSON_PROPERTY_ICEBERG_QTY,
  OrderDetails.JSON_PROPERTY_TIME,
  OrderDetails.JSON_PROPERTY_UPDATE_TIME,
  OrderDetails.JSON_PROPERTY_IS_WORKING,
  OrderDetails.JSON_PROPERTY_WORKING_TIME,
  OrderDetails.JSON_PROPERTY_ORIG_QUOTE_ORDER_QTY,
  OrderDetails.JSON_PROPERTY_SELF_TRADE_PREVENTION_MODE,
  OrderDetails.JSON_PROPERTY_PREVENTED_MATCH_ID,
  OrderDetails.JSON_PROPERTY_PREVENTED_QUANTITY
})
@JsonTypeName("orderDetails")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class OrderDetails {
  public static final String JSON_PROPERTY_SYMBOL = "symbol";
  private String symbol;

  public static final String JSON_PROPERTY_ORDER_ID = "orderId";
  private Long orderId;

  public static final String JSON_PROPERTY_ORDER_LIST_ID = "orderListId";
  private Long orderListId;

  public static final String JSON_PROPERTY_CLIENT_ORDER_ID = "clientOrderId";
  private String clientOrderId;

  public static final String JSON_PROPERTY_PRICE = "price";
  private String price;

  public static final String JSON_PROPERTY_ORIG_QTY = "origQty";
  private String origQty;

  public static final String JSON_PROPERTY_EXECUTED_QTY = "executedQty";
  private String executedQty;

  public static final String JSON_PROPERTY_CUMMULATIVE_QUOTE_QTY = "cummulativeQuoteQty";
  private String cummulativeQuoteQty;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_TIME_IN_FORCE = "timeInForce";
  private String timeInForce;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public static final String JSON_PROPERTY_SIDE = "side";
  private String side;

  public static final String JSON_PROPERTY_STOP_PRICE = "stopPrice";
  private String stopPrice;

  public static final String JSON_PROPERTY_ICEBERG_QTY = "icebergQty";
  private String icebergQty;

  public static final String JSON_PROPERTY_TIME = "time";
  private Long time;

  public static final String JSON_PROPERTY_UPDATE_TIME = "updateTime";
  private Long updateTime;

  public static final String JSON_PROPERTY_IS_WORKING = "isWorking";
  private Boolean isWorking;

  public static final String JSON_PROPERTY_WORKING_TIME = "workingTime";
  private Long workingTime;

  public static final String JSON_PROPERTY_ORIG_QUOTE_ORDER_QTY = "origQuoteOrderQty";
  private String origQuoteOrderQty;

  public static final String JSON_PROPERTY_SELF_TRADE_PREVENTION_MODE = "selfTradePreventionMode";
  private String selfTradePreventionMode;

  public static final String JSON_PROPERTY_PREVENTED_MATCH_ID = "preventedMatchId";
  private Integer preventedMatchId;

  public static final String JSON_PROPERTY_PREVENTED_QUANTITY = "preventedQuantity";
  private String preventedQuantity;

  public OrderDetails() {
  }

  public OrderDetails symbol(String symbol) {
    
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "LTCBTC", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSymbol() {
    return symbol;
  }


  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }


  public OrderDetails orderId(Long orderId) {
    
    this.orderId = orderId;
    return this;
  }

   /**
   * Get orderId
   * @return orderId
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getOrderId() {
    return orderId;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrderId(Long orderId) {
    this.orderId = orderId;
  }


  public OrderDetails orderListId(Long orderListId) {
    
    this.orderListId = orderListId;
    return this;
  }

   /**
   * Unless OCO, value will be -1
   * @return orderListId
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "-1", required = true, value = "Unless OCO, value will be -1")
  @JsonProperty(JSON_PROPERTY_ORDER_LIST_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getOrderListId() {
    return orderListId;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_LIST_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrderListId(Long orderListId) {
    this.orderListId = orderListId;
  }


  public OrderDetails clientOrderId(String clientOrderId) {
    
    this.clientOrderId = clientOrderId;
    return this;
  }

   /**
   * Get clientOrderId
   * @return clientOrderId
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "myOrder1", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CLIENT_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getClientOrderId() {
    return clientOrderId;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClientOrderId(String clientOrderId) {
    this.clientOrderId = clientOrderId;
  }


  public OrderDetails price(String price) {
    
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.1", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPrice() {
    return price;
  }


  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrice(String price) {
    this.price = price;
  }


  public OrderDetails origQty(String origQty) {
    
    this.origQty = origQty;
    return this;
  }

   /**
   * Get origQty
   * @return origQty
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1.0", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ORIG_QTY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOrigQty() {
    return origQty;
  }


  @JsonProperty(JSON_PROPERTY_ORIG_QTY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrigQty(String origQty) {
    this.origQty = origQty;
  }


  public OrderDetails executedQty(String executedQty) {
    
    this.executedQty = executedQty;
    return this;
  }

   /**
   * Get executedQty
   * @return executedQty
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.0", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_EXECUTED_QTY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExecutedQty() {
    return executedQty;
  }


  @JsonProperty(JSON_PROPERTY_EXECUTED_QTY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExecutedQty(String executedQty) {
    this.executedQty = executedQty;
  }


  public OrderDetails cummulativeQuoteQty(String cummulativeQuoteQty) {
    
    this.cummulativeQuoteQty = cummulativeQuoteQty;
    return this;
  }

   /**
   * Get cummulativeQuoteQty
   * @return cummulativeQuoteQty
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.0", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CUMMULATIVE_QUOTE_QTY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCummulativeQuoteQty() {
    return cummulativeQuoteQty;
  }


  @JsonProperty(JSON_PROPERTY_CUMMULATIVE_QUOTE_QTY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCummulativeQuoteQty(String cummulativeQuoteQty) {
    this.cummulativeQuoteQty = cummulativeQuoteQty;
  }


  public OrderDetails status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "NEW", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(String status) {
    this.status = status;
  }


  public OrderDetails timeInForce(String timeInForce) {
    
    this.timeInForce = timeInForce;
    return this;
  }

   /**
   * Get timeInForce
   * @return timeInForce
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "GTC", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TIME_IN_FORCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTimeInForce() {
    return timeInForce;
  }


  @JsonProperty(JSON_PROPERTY_TIME_IN_FORCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTimeInForce(String timeInForce) {
    this.timeInForce = timeInForce;
  }


  public OrderDetails type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "LIMIT", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(String type) {
    this.type = type;
  }


  public OrderDetails side(String side) {
    
    this.side = side;
    return this;
  }

   /**
   * Get side
   * @return side
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "BUY", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SIDE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSide() {
    return side;
  }


  @JsonProperty(JSON_PROPERTY_SIDE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSide(String side) {
    this.side = side;
  }


  public OrderDetails stopPrice(String stopPrice) {
    
    this.stopPrice = stopPrice;
    return this;
  }

   /**
   * Get stopPrice
   * @return stopPrice
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.0", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_STOP_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStopPrice() {
    return stopPrice;
  }


  @JsonProperty(JSON_PROPERTY_STOP_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStopPrice(String stopPrice) {
    this.stopPrice = stopPrice;
  }


  public OrderDetails icebergQty(String icebergQty) {
    
    this.icebergQty = icebergQty;
    return this;
  }

   /**
   * Get icebergQty
   * @return icebergQty
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.0", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ICEBERG_QTY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIcebergQty() {
    return icebergQty;
  }


  @JsonProperty(JSON_PROPERTY_ICEBERG_QTY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIcebergQty(String icebergQty) {
    this.icebergQty = icebergQty;
  }


  public OrderDetails time(Long time) {
    
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1499827319559", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getTime() {
    return time;
  }


  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTime(Long time) {
    this.time = time;
  }


  public OrderDetails updateTime(Long updateTime) {
    
    this.updateTime = updateTime;
    return this;
  }

   /**
   * Get updateTime
   * @return updateTime
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1499827319559", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_UPDATE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getUpdateTime() {
    return updateTime;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdateTime(Long updateTime) {
    this.updateTime = updateTime;
  }


  public OrderDetails isWorking(Boolean isWorking) {
    
    this.isWorking = isWorking;
    return this;
  }

   /**
   * Get isWorking
   * @return isWorking
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_IS_WORKING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsWorking() {
    return isWorking;
  }


  @JsonProperty(JSON_PROPERTY_IS_WORKING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsWorking(Boolean isWorking) {
    this.isWorking = isWorking;
  }


  public OrderDetails workingTime(Long workingTime) {
    
    this.workingTime = workingTime;
    return this;
  }

   /**
   * Get workingTime
   * @return workingTime
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1499827319559", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_WORKING_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getWorkingTime() {
    return workingTime;
  }


  @JsonProperty(JSON_PROPERTY_WORKING_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWorkingTime(Long workingTime) {
    this.workingTime = workingTime;
  }


  public OrderDetails origQuoteOrderQty(String origQuoteOrderQty) {
    
    this.origQuoteOrderQty = origQuoteOrderQty;
    return this;
  }

   /**
   * Get origQuoteOrderQty
   * @return origQuoteOrderQty
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.00000000", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ORIG_QUOTE_ORDER_QTY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOrigQuoteOrderQty() {
    return origQuoteOrderQty;
  }


  @JsonProperty(JSON_PROPERTY_ORIG_QUOTE_ORDER_QTY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrigQuoteOrderQty(String origQuoteOrderQty) {
    this.origQuoteOrderQty = origQuoteOrderQty;
  }


  public OrderDetails selfTradePreventionMode(String selfTradePreventionMode) {
    
    this.selfTradePreventionMode = selfTradePreventionMode;
    return this;
  }

   /**
   * Get selfTradePreventionMode
   * @return selfTradePreventionMode
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "NONE", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SELF_TRADE_PREVENTION_MODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSelfTradePreventionMode() {
    return selfTradePreventionMode;
  }


  @JsonProperty(JSON_PROPERTY_SELF_TRADE_PREVENTION_MODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSelfTradePreventionMode(String selfTradePreventionMode) {
    this.selfTradePreventionMode = selfTradePreventionMode;
  }


  public OrderDetails preventedMatchId(Integer preventedMatchId) {
    
    this.preventedMatchId = preventedMatchId;
    return this;
  }

   /**
   * Get preventedMatchId
   * @return preventedMatchId
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(example = "0", value = "")
  @JsonProperty(JSON_PROPERTY_PREVENTED_MATCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPreventedMatchId() {
    return preventedMatchId;
  }


  @JsonProperty(JSON_PROPERTY_PREVENTED_MATCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreventedMatchId(Integer preventedMatchId) {
    this.preventedMatchId = preventedMatchId;
  }


  public OrderDetails preventedQuantity(String preventedQuantity) {
    
    this.preventedQuantity = preventedQuantity;
    return this;
  }

   /**
   * Get preventedQuantity
   * @return preventedQuantity
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(example = "1.200000", value = "")
  @JsonProperty(JSON_PROPERTY_PREVENTED_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPreventedQuantity() {
    return preventedQuantity;
  }


  @JsonProperty(JSON_PROPERTY_PREVENTED_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreventedQuantity(String preventedQuantity) {
    this.preventedQuantity = preventedQuantity;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderDetails orderDetails = (OrderDetails) o;
    return Objects.equals(this.symbol, orderDetails.symbol) &&
        Objects.equals(this.orderId, orderDetails.orderId) &&
        Objects.equals(this.orderListId, orderDetails.orderListId) &&
        Objects.equals(this.clientOrderId, orderDetails.clientOrderId) &&
        Objects.equals(this.price, orderDetails.price) &&
        Objects.equals(this.origQty, orderDetails.origQty) &&
        Objects.equals(this.executedQty, orderDetails.executedQty) &&
        Objects.equals(this.cummulativeQuoteQty, orderDetails.cummulativeQuoteQty) &&
        Objects.equals(this.status, orderDetails.status) &&
        Objects.equals(this.timeInForce, orderDetails.timeInForce) &&
        Objects.equals(this.type, orderDetails.type) &&
        Objects.equals(this.side, orderDetails.side) &&
        Objects.equals(this.stopPrice, orderDetails.stopPrice) &&
        Objects.equals(this.icebergQty, orderDetails.icebergQty) &&
        Objects.equals(this.time, orderDetails.time) &&
        Objects.equals(this.updateTime, orderDetails.updateTime) &&
        Objects.equals(this.isWorking, orderDetails.isWorking) &&
        Objects.equals(this.workingTime, orderDetails.workingTime) &&
        Objects.equals(this.origQuoteOrderQty, orderDetails.origQuoteOrderQty) &&
        Objects.equals(this.selfTradePreventionMode, orderDetails.selfTradePreventionMode) &&
        Objects.equals(this.preventedMatchId, orderDetails.preventedMatchId) &&
        Objects.equals(this.preventedQuantity, orderDetails.preventedQuantity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, orderId, orderListId, clientOrderId, price, origQty, executedQty, cummulativeQuoteQty, status, timeInForce, type, side, stopPrice, icebergQty, time, updateTime, isWorking, workingTime, origQuoteOrderQty, selfTradePreventionMode, preventedMatchId, preventedQuantity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderDetails {\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    orderListId: ").append(toIndentedString(orderListId)).append("\n");
    sb.append("    clientOrderId: ").append(toIndentedString(clientOrderId)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    origQty: ").append(toIndentedString(origQty)).append("\n");
    sb.append("    executedQty: ").append(toIndentedString(executedQty)).append("\n");
    sb.append("    cummulativeQuoteQty: ").append(toIndentedString(cummulativeQuoteQty)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    timeInForce: ").append(toIndentedString(timeInForce)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    side: ").append(toIndentedString(side)).append("\n");
    sb.append("    stopPrice: ").append(toIndentedString(stopPrice)).append("\n");
    sb.append("    icebergQty: ").append(toIndentedString(icebergQty)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("    isWorking: ").append(toIndentedString(isWorking)).append("\n");
    sb.append("    workingTime: ").append(toIndentedString(workingTime)).append("\n");
    sb.append("    origQuoteOrderQty: ").append(toIndentedString(origQuoteOrderQty)).append("\n");
    sb.append("    selfTradePreventionMode: ").append(toIndentedString(selfTradePreventionMode)).append("\n");
    sb.append("    preventedMatchId: ").append(toIndentedString(preventedMatchId)).append("\n");
    sb.append("    preventedQuantity: ").append(toIndentedString(preventedQuantity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

