/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RepaymentInfo2
 */
@JsonPropertyOrder({
  RepaymentInfo2.JSON_PROPERTY_LOAN_COIN,
  RepaymentInfo2.JSON_PROPERTY_COLLATERAL_COIN,
  RepaymentInfo2.JSON_PROPERTY_REPAY_STATUS
})
@JsonTypeName("repaymentInfo2")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class RepaymentInfo2 {
  public static final String JSON_PROPERTY_LOAN_COIN = "loanCoin";
  private String loanCoin;

  public static final String JSON_PROPERTY_COLLATERAL_COIN = "collateralCoin";
  private String collateralCoin;

  public static final String JSON_PROPERTY_REPAY_STATUS = "repayStatus";
  private String repayStatus;

  public RepaymentInfo2() {
  }

  public RepaymentInfo2 loanCoin(String loanCoin) {
    
    this.loanCoin = loanCoin;
    return this;
  }

   /**
   * Get loanCoin
   * @return loanCoin
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "BUSD", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LOAN_COIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLoanCoin() {
    return loanCoin;
  }


  @JsonProperty(JSON_PROPERTY_LOAN_COIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLoanCoin(String loanCoin) {
    this.loanCoin = loanCoin;
  }


  public RepaymentInfo2 collateralCoin(String collateralCoin) {
    
    this.collateralCoin = collateralCoin;
    return this;
  }

   /**
   * Get collateralCoin
   * @return collateralCoin
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "BNB", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_COLLATERAL_COIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCollateralCoin() {
    return collateralCoin;
  }


  @JsonProperty(JSON_PROPERTY_COLLATERAL_COIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCollateralCoin(String collateralCoin) {
    this.collateralCoin = collateralCoin;
  }


  public RepaymentInfo2 repayStatus(String repayStatus) {
    
    this.repayStatus = repayStatus;
    return this;
  }

   /**
   * Get repayStatus
   * @return repayStatus
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "Repaying", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_REPAY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRepayStatus() {
    return repayStatus;
  }


  @JsonProperty(JSON_PROPERTY_REPAY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRepayStatus(String repayStatus) {
    this.repayStatus = repayStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RepaymentInfo2 repaymentInfo2 = (RepaymentInfo2) o;
    return Objects.equals(this.loanCoin, repaymentInfo2.loanCoin) &&
        Objects.equals(this.collateralCoin, repaymentInfo2.collateralCoin) &&
        Objects.equals(this.repayStatus, repaymentInfo2.repayStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loanCoin, collateralCoin, repayStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RepaymentInfo2 {\n");
    sb.append("    loanCoin: ").append(toIndentedString(loanCoin)).append("\n");
    sb.append("    collateralCoin: ").append(toIndentedString(collateralCoin)).append("\n");
    sb.append("    repayStatus: ").append(toIndentedString(repayStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

