/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner
 */
@JsonPropertyOrder({
  SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner.JSON_PROPERTY_FROM_EMAIL,
  SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner.JSON_PROPERTY_FROM_ACCOUNT_TYPE,
  SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner.JSON_PROPERTY_TO_EMAIL,
  SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner.JSON_PROPERTY_TO_ACCOUNT_TYPE,
  SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner.JSON_PROPERTY_ASSET,
  SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner.JSON_PROPERTY_AMOUNT,
  SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner.JSON_PROPERTY_SCHEDULED_DATA,
  SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner.JSON_PROPERTY_CREATE_TIME,
  SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner.JSON_PROPERTY_STATUS,
  SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner.JSON_PROPERTY_TRAN_ID
})
@JsonTypeName("_sapi_v1_managed_subaccount_query_trans_log_get_200_response_managerSubTransferHistoryVos_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner {
  public static final String JSON_PROPERTY_FROM_EMAIL = "fromEmail";
  private String fromEmail;

  public static final String JSON_PROPERTY_FROM_ACCOUNT_TYPE = "fromAccountType";
  private String fromAccountType;

  public static final String JSON_PROPERTY_TO_EMAIL = "toEmail";
  private String toEmail;

  public static final String JSON_PROPERTY_TO_ACCOUNT_TYPE = "toAccountType";
  private String toAccountType;

  public static final String JSON_PROPERTY_ASSET = "asset";
  private String asset;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private String amount;

  public static final String JSON_PROPERTY_SCHEDULED_DATA = "scheduledData";
  private Long scheduledData;

  public static final String JSON_PROPERTY_CREATE_TIME = "createTime";
  private Long createTime;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_TRAN_ID = "tranId";
  private Long tranId;

  public SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner() {
  }

  public SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner fromEmail(String fromEmail) {
    
    this.fromEmail = fromEmail;
    return this;
  }

   /**
   * Get fromEmail
   * @return fromEmail
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "test_0_virtual@kq3kno9imanagedsub.com", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_FROM_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFromEmail() {
    return fromEmail;
  }


  @JsonProperty(JSON_PROPERTY_FROM_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFromEmail(String fromEmail) {
    this.fromEmail = fromEmail;
  }


  public SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner fromAccountType(String fromAccountType) {
    
    this.fromAccountType = fromAccountType;
    return this;
  }

   /**
   * Get fromAccountType
   * @return fromAccountType
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "SPOT", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_FROM_ACCOUNT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFromAccountType() {
    return fromAccountType;
  }


  @JsonProperty(JSON_PROPERTY_FROM_ACCOUNT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFromAccountType(String fromAccountType) {
    this.fromAccountType = fromAccountType;
  }


  public SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner toEmail(String toEmail) {
    
    this.toEmail = toEmail;
    return this;
  }

   /**
   * Get toEmail
   * @return toEmail
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "wdywl0lddakh@test.com", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TO_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getToEmail() {
    return toEmail;
  }


  @JsonProperty(JSON_PROPERTY_TO_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToEmail(String toEmail) {
    this.toEmail = toEmail;
  }


  public SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner toAccountType(String toAccountType) {
    
    this.toAccountType = toAccountType;
    return this;
  }

   /**
   * Get toAccountType
   * @return toAccountType
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "SPOT", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TO_ACCOUNT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getToAccountType() {
    return toAccountType;
  }


  @JsonProperty(JSON_PROPERTY_TO_ACCOUNT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToAccountType(String toAccountType) {
    this.toAccountType = toAccountType;
  }


  public SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner asset(String asset) {
    
    this.asset = asset;
    return this;
  }

   /**
   * Get asset
   * @return asset
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "BNB", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ASSET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAsset() {
    return asset;
  }


  @JsonProperty(JSON_PROPERTY_ASSET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAsset(String asset) {
    this.asset = asset;
  }


  public SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner amount(String amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.01", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(String amount) {
    this.amount = amount;
  }


  public SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner scheduledData(Long scheduledData) {
    
    this.scheduledData = scheduledData;
    return this;
  }

   /**
   * Get scheduledData
   * @return scheduledData
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1679416673000", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SCHEDULED_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getScheduledData() {
    return scheduledData;
  }


  @JsonProperty(JSON_PROPERTY_SCHEDULED_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setScheduledData(Long scheduledData) {
    this.scheduledData = scheduledData;
  }


  public SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner createTime(Long createTime) {
    
    this.createTime = createTime;
    return this;
  }

   /**
   * Get createTime
   * @return createTime
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1679416673000", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CREATE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getCreateTime() {
    return createTime;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreateTime(Long createTime) {
    this.createTime = createTime;
  }


  public SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "SUCCESS", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(String status) {
    this.status = status;
  }


  public SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner tranId(Long tranId) {
    
    this.tranId = tranId;
    return this;
  }

   /**
   * Get tranId
   * @return tranId
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "91077779", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TRAN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getTranId() {
    return tranId;
  }


  @JsonProperty(JSON_PROPERTY_TRAN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTranId(Long tranId) {
    this.tranId = tranId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner sapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner = (SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner) o;
    return Objects.equals(this.fromEmail, sapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner.fromEmail) &&
        Objects.equals(this.fromAccountType, sapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner.fromAccountType) &&
        Objects.equals(this.toEmail, sapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner.toEmail) &&
        Objects.equals(this.toAccountType, sapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner.toAccountType) &&
        Objects.equals(this.asset, sapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner.asset) &&
        Objects.equals(this.amount, sapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner.amount) &&
        Objects.equals(this.scheduledData, sapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner.scheduledData) &&
        Objects.equals(this.createTime, sapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner.createTime) &&
        Objects.equals(this.status, sapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner.status) &&
        Objects.equals(this.tranId, sapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner.tranId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fromEmail, fromAccountType, toEmail, toAccountType, asset, amount, scheduledData, createTime, status, tranId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SapiV1ManagedSubaccountQueryTransLogGet200ResponseManagerSubTransferHistoryVosInner {\n");
    sb.append("    fromEmail: ").append(toIndentedString(fromEmail)).append("\n");
    sb.append("    fromAccountType: ").append(toIndentedString(fromAccountType)).append("\n");
    sb.append("    toEmail: ").append(toIndentedString(toEmail)).append("\n");
    sb.append("    toAccountType: ").append(toIndentedString(toAccountType)).append("\n");
    sb.append("    asset: ").append(toIndentedString(asset)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    scheduledData: ").append(toIndentedString(scheduledData)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tranId: ").append(toIndentedString(tranId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

