/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SapiV1BlvtSubscribePost200Response
 */
@JsonPropertyOrder({
  SapiV1BlvtSubscribePost200Response.JSON_PROPERTY_ID,
  SapiV1BlvtSubscribePost200Response.JSON_PROPERTY_STATUS,
  SapiV1BlvtSubscribePost200Response.JSON_PROPERTY_TOKEN_NAME,
  SapiV1BlvtSubscribePost200Response.JSON_PROPERTY_AMOUNT,
  SapiV1BlvtSubscribePost200Response.JSON_PROPERTY_COST,
  SapiV1BlvtSubscribePost200Response.JSON_PROPERTY_TIMESTAMP
})
@JsonTypeName("_sapi_v1_blvt_subscribe_post_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SapiV1BlvtSubscribePost200Response {
  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_TOKEN_NAME = "tokenName";
  private String tokenName;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private String amount;

  public static final String JSON_PROPERTY_COST = "cost";
  private String cost;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  private Long timestamp;

  public SapiV1BlvtSubscribePost200Response() {
  }

  public SapiV1BlvtSubscribePost200Response id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "123", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(Long id) {
    this.id = id;
  }


  public SapiV1BlvtSubscribePost200Response status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * S, P, and F for \&quot;success\&quot;, \&quot;pending\&quot;, and \&quot;failure\&quot;
   * @return status
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "S", required = true, value = "S, P, and F for \"success\", \"pending\", and \"failure\"")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(String status) {
    this.status = status;
  }


  public SapiV1BlvtSubscribePost200Response tokenName(String tokenName) {
    
    this.tokenName = tokenName;
    return this;
  }

   /**
   * Get tokenName
   * @return tokenName
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "LINKUP", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TOKEN_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTokenName() {
    return tokenName;
  }


  @JsonProperty(JSON_PROPERTY_TOKEN_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTokenName(String tokenName) {
    this.tokenName = tokenName;
  }


  public SapiV1BlvtSubscribePost200Response amount(String amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * subscribed token amount
   * @return amount
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.9559090500", required = true, value = "subscribed token amount")
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(String amount) {
    this.amount = amount;
  }


  public SapiV1BlvtSubscribePost200Response cost(String cost) {
    
    this.cost = cost;
    return this;
  }

   /**
   * subscription cost in usdt
   * @return cost
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "9.99999995", required = true, value = "subscription cost in usdt")
  @JsonProperty(JSON_PROPERTY_COST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCost() {
    return cost;
  }


  @JsonProperty(JSON_PROPERTY_COST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCost(String cost) {
    this.cost = cost;
  }


  public SapiV1BlvtSubscribePost200Response timestamp(Long timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1600249972899", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getTimestamp() {
    return timestamp;
  }


  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTimestamp(Long timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SapiV1BlvtSubscribePost200Response sapiV1BlvtSubscribePost200Response = (SapiV1BlvtSubscribePost200Response) o;
    return Objects.equals(this.id, sapiV1BlvtSubscribePost200Response.id) &&
        Objects.equals(this.status, sapiV1BlvtSubscribePost200Response.status) &&
        Objects.equals(this.tokenName, sapiV1BlvtSubscribePost200Response.tokenName) &&
        Objects.equals(this.amount, sapiV1BlvtSubscribePost200Response.amount) &&
        Objects.equals(this.cost, sapiV1BlvtSubscribePost200Response.cost) &&
        Objects.equals(this.timestamp, sapiV1BlvtSubscribePost200Response.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, status, tokenName, amount, cost, timestamp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SapiV1BlvtSubscribePost200Response {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tokenName: ").append(toIndentedString(tokenName)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

