/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SapiV1MarginIsolatedAccountLimitGet200Response
 */
@JsonPropertyOrder({
  SapiV1MarginIsolatedAccountLimitGet200Response.JSON_PROPERTY_ENABLED_ACCOUNT,
  SapiV1MarginIsolatedAccountLimitGet200Response.JSON_PROPERTY_MAX_ACCOUNT
})
@JsonTypeName("_sapi_v1_margin_isolated_accountLimit_get_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SapiV1MarginIsolatedAccountLimitGet200Response {
  public static final String JSON_PROPERTY_ENABLED_ACCOUNT = "enabledAccount";
  private Long enabledAccount;

  public static final String JSON_PROPERTY_MAX_ACCOUNT = "maxAccount";
  private Long maxAccount;

  public SapiV1MarginIsolatedAccountLimitGet200Response() {
  }

  public SapiV1MarginIsolatedAccountLimitGet200Response enabledAccount(Long enabledAccount) {
    
    this.enabledAccount = enabledAccount;
    return this;
  }

   /**
   * Get enabledAccount
   * @return enabledAccount
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "5", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ENABLED_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getEnabledAccount() {
    return enabledAccount;
  }


  @JsonProperty(JSON_PROPERTY_ENABLED_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEnabledAccount(Long enabledAccount) {
    this.enabledAccount = enabledAccount;
  }


  public SapiV1MarginIsolatedAccountLimitGet200Response maxAccount(Long maxAccount) {
    
    this.maxAccount = maxAccount;
    return this;
  }

   /**
   * Get maxAccount
   * @return maxAccount
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "20", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_MAX_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getMaxAccount() {
    return maxAccount;
  }


  @JsonProperty(JSON_PROPERTY_MAX_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMaxAccount(Long maxAccount) {
    this.maxAccount = maxAccount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SapiV1MarginIsolatedAccountLimitGet200Response sapiV1MarginIsolatedAccountLimitGet200Response = (SapiV1MarginIsolatedAccountLimitGet200Response) o;
    return Objects.equals(this.enabledAccount, sapiV1MarginIsolatedAccountLimitGet200Response.enabledAccount) &&
        Objects.equals(this.maxAccount, sapiV1MarginIsolatedAccountLimitGet200Response.maxAccount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabledAccount, maxAccount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SapiV1MarginIsolatedAccountLimitGet200Response {\n");
    sb.append("    enabledAccount: ").append(toIndentedString(enabledAccount)).append("\n");
    sb.append("    maxAccount: ").append(toIndentedString(maxAccount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

