/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SapiV1LoanLoanableDataGet200ResponseRowsInner
 */
@JsonPropertyOrder({
  SapiV1LoanLoanableDataGet200ResponseRowsInner.JSON_PROPERTY_LOAN_COIN,
  SapiV1LoanLoanableDataGet200ResponseRowsInner.JSON_PROPERTY_7D_HOURLY_INTEREST_RATE,
  SapiV1LoanLoanableDataGet200ResponseRowsInner.JSON_PROPERTY_7D_DAILY_INTEREST_RATE,
  SapiV1LoanLoanableDataGet200ResponseRowsInner.JSON_PROPERTY_14D_HOURLY_INTEREST_RATE,
  SapiV1LoanLoanableDataGet200ResponseRowsInner.JSON_PROPERTY_14D_DAILY_INTEREST_RATE,
  SapiV1LoanLoanableDataGet200ResponseRowsInner.JSON_PROPERTY_30D_HOURLY_INTEREST_RATE,
  SapiV1LoanLoanableDataGet200ResponseRowsInner.JSON_PROPERTY_30D_DAILY_INTEREST_RATE,
  SapiV1LoanLoanableDataGet200ResponseRowsInner.JSON_PROPERTY_90D_HOURLY_INTEREST_RATE,
  SapiV1LoanLoanableDataGet200ResponseRowsInner.JSON_PROPERTY_90D_DAILY_INTEREST_RATE,
  SapiV1LoanLoanableDataGet200ResponseRowsInner.JSON_PROPERTY_180D_HOURLY_INTEREST_RATE,
  SapiV1LoanLoanableDataGet200ResponseRowsInner.JSON_PROPERTY_180D_DAILY_INTEREST_RATE,
  SapiV1LoanLoanableDataGet200ResponseRowsInner.JSON_PROPERTY_MIN_LIMIT,
  SapiV1LoanLoanableDataGet200ResponseRowsInner.JSON_PROPERTY_MAX_LIMIT,
  SapiV1LoanLoanableDataGet200ResponseRowsInner.JSON_PROPERTY_VIP_LEVEL
})
@JsonTypeName("_sapi_v1_loan_loanable_data_get_200_response_rows_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SapiV1LoanLoanableDataGet200ResponseRowsInner {
  public static final String JSON_PROPERTY_LOAN_COIN = "loanCoin";
  private String loanCoin;

  public static final String JSON_PROPERTY_7D_HOURLY_INTEREST_RATE = "_7dHourlyInterestRate";
  private String _7dHourlyInterestRate;

  public static final String JSON_PROPERTY_7D_DAILY_INTEREST_RATE = "_7dDailyInterestRate";
  private String _7dDailyInterestRate;

  public static final String JSON_PROPERTY_14D_HOURLY_INTEREST_RATE = "_14dHourlyInterestRate";
  private String _14dHourlyInterestRate;

  public static final String JSON_PROPERTY_14D_DAILY_INTEREST_RATE = "_14dDailyInterestRate";
  private String _14dDailyInterestRate;

  public static final String JSON_PROPERTY_30D_HOURLY_INTEREST_RATE = "_30dHourlyInterestRate";
  private String _30dHourlyInterestRate;

  public static final String JSON_PROPERTY_30D_DAILY_INTEREST_RATE = "_30dDailyInterestRate";
  private String _30dDailyInterestRate;

  public static final String JSON_PROPERTY_90D_HOURLY_INTEREST_RATE = "_90dHourlyInterestRate";
  private String _90dHourlyInterestRate;

  public static final String JSON_PROPERTY_90D_DAILY_INTEREST_RATE = "_90dDailyInterestRate";
  private String _90dDailyInterestRate;

  public static final String JSON_PROPERTY_180D_HOURLY_INTEREST_RATE = "_180dHourlyInterestRate";
  private String _180dHourlyInterestRate;

  public static final String JSON_PROPERTY_180D_DAILY_INTEREST_RATE = "_180dDailyInterestRate";
  private String _180dDailyInterestRate;

  public static final String JSON_PROPERTY_MIN_LIMIT = "minLimit";
  private String minLimit;

  public static final String JSON_PROPERTY_MAX_LIMIT = "maxLimit";
  private String maxLimit;

  public static final String JSON_PROPERTY_VIP_LEVEL = "vipLevel";
  private Integer vipLevel;

  public SapiV1LoanLoanableDataGet200ResponseRowsInner() {
  }

  public SapiV1LoanLoanableDataGet200ResponseRowsInner loanCoin(String loanCoin) {
    
    this.loanCoin = loanCoin;
    return this;
  }

   /**
   * Get loanCoin
   * @return loanCoin
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "BUSD", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LOAN_COIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLoanCoin() {
    return loanCoin;
  }


  @JsonProperty(JSON_PROPERTY_LOAN_COIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLoanCoin(String loanCoin) {
    this.loanCoin = loanCoin;
  }


  public SapiV1LoanLoanableDataGet200ResponseRowsInner _7dHourlyInterestRate(String _7dHourlyInterestRate) {
    
    this._7dHourlyInterestRate = _7dHourlyInterestRate;
    return this;
  }

   /**
   * Get _7dHourlyInterestRate
   * @return _7dHourlyInterestRate
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.00000491", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_7D_HOURLY_INTEREST_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String get7dHourlyInterestRate() {
    return _7dHourlyInterestRate;
  }


  @JsonProperty(JSON_PROPERTY_7D_HOURLY_INTEREST_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void set7dHourlyInterestRate(String _7dHourlyInterestRate) {
    this._7dHourlyInterestRate = _7dHourlyInterestRate;
  }


  public SapiV1LoanLoanableDataGet200ResponseRowsInner _7dDailyInterestRate(String _7dDailyInterestRate) {
    
    this._7dDailyInterestRate = _7dDailyInterestRate;
    return this;
  }

   /**
   * Get _7dDailyInterestRate
   * @return _7dDailyInterestRate
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.000118", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_7D_DAILY_INTEREST_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String get7dDailyInterestRate() {
    return _7dDailyInterestRate;
  }


  @JsonProperty(JSON_PROPERTY_7D_DAILY_INTEREST_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void set7dDailyInterestRate(String _7dDailyInterestRate) {
    this._7dDailyInterestRate = _7dDailyInterestRate;
  }


  public SapiV1LoanLoanableDataGet200ResponseRowsInner _14dHourlyInterestRate(String _14dHourlyInterestRate) {
    
    this._14dHourlyInterestRate = _14dHourlyInterestRate;
    return this;
  }

   /**
   * Get _14dHourlyInterestRate
   * @return _14dHourlyInterestRate
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.00000491", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_14D_HOURLY_INTEREST_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String get14dHourlyInterestRate() {
    return _14dHourlyInterestRate;
  }


  @JsonProperty(JSON_PROPERTY_14D_HOURLY_INTEREST_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void set14dHourlyInterestRate(String _14dHourlyInterestRate) {
    this._14dHourlyInterestRate = _14dHourlyInterestRate;
  }


  public SapiV1LoanLoanableDataGet200ResponseRowsInner _14dDailyInterestRate(String _14dDailyInterestRate) {
    
    this._14dDailyInterestRate = _14dDailyInterestRate;
    return this;
  }

   /**
   * Get _14dDailyInterestRate
   * @return _14dDailyInterestRate
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.000118", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_14D_DAILY_INTEREST_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String get14dDailyInterestRate() {
    return _14dDailyInterestRate;
  }


  @JsonProperty(JSON_PROPERTY_14D_DAILY_INTEREST_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void set14dDailyInterestRate(String _14dDailyInterestRate) {
    this._14dDailyInterestRate = _14dDailyInterestRate;
  }


  public SapiV1LoanLoanableDataGet200ResponseRowsInner _30dHourlyInterestRate(String _30dHourlyInterestRate) {
    
    this._30dHourlyInterestRate = _30dHourlyInterestRate;
    return this;
  }

   /**
   * Get _30dHourlyInterestRate
   * @return _30dHourlyInterestRate
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.00000567", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_30D_HOURLY_INTEREST_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String get30dHourlyInterestRate() {
    return _30dHourlyInterestRate;
  }


  @JsonProperty(JSON_PROPERTY_30D_HOURLY_INTEREST_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void set30dHourlyInterestRate(String _30dHourlyInterestRate) {
    this._30dHourlyInterestRate = _30dHourlyInterestRate;
  }


  public SapiV1LoanLoanableDataGet200ResponseRowsInner _30dDailyInterestRate(String _30dDailyInterestRate) {
    
    this._30dDailyInterestRate = _30dDailyInterestRate;
    return this;
  }

   /**
   * Get _30dDailyInterestRate
   * @return _30dDailyInterestRate
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.000136", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_30D_DAILY_INTEREST_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String get30dDailyInterestRate() {
    return _30dDailyInterestRate;
  }


  @JsonProperty(JSON_PROPERTY_30D_DAILY_INTEREST_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void set30dDailyInterestRate(String _30dDailyInterestRate) {
    this._30dDailyInterestRate = _30dDailyInterestRate;
  }


  public SapiV1LoanLoanableDataGet200ResponseRowsInner _90dHourlyInterestRate(String _90dHourlyInterestRate) {
    
    this._90dHourlyInterestRate = _90dHourlyInterestRate;
    return this;
  }

   /**
   * Get _90dHourlyInterestRate
   * @return _90dHourlyInterestRate
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.00000596", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_90D_HOURLY_INTEREST_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String get90dHourlyInterestRate() {
    return _90dHourlyInterestRate;
  }


  @JsonProperty(JSON_PROPERTY_90D_HOURLY_INTEREST_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void set90dHourlyInterestRate(String _90dHourlyInterestRate) {
    this._90dHourlyInterestRate = _90dHourlyInterestRate;
  }


  public SapiV1LoanLoanableDataGet200ResponseRowsInner _90dDailyInterestRate(String _90dDailyInterestRate) {
    
    this._90dDailyInterestRate = _90dDailyInterestRate;
    return this;
  }

   /**
   * Get _90dDailyInterestRate
   * @return _90dDailyInterestRate
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.000143", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_90D_DAILY_INTEREST_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String get90dDailyInterestRate() {
    return _90dDailyInterestRate;
  }


  @JsonProperty(JSON_PROPERTY_90D_DAILY_INTEREST_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void set90dDailyInterestRate(String _90dDailyInterestRate) {
    this._90dDailyInterestRate = _90dDailyInterestRate;
  }


  public SapiV1LoanLoanableDataGet200ResponseRowsInner _180dHourlyInterestRate(String _180dHourlyInterestRate) {
    
    this._180dHourlyInterestRate = _180dHourlyInterestRate;
    return this;
  }

   /**
   * Get _180dHourlyInterestRate
   * @return _180dHourlyInterestRate
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.00000631", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_180D_HOURLY_INTEREST_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String get180dHourlyInterestRate() {
    return _180dHourlyInterestRate;
  }


  @JsonProperty(JSON_PROPERTY_180D_HOURLY_INTEREST_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void set180dHourlyInterestRate(String _180dHourlyInterestRate) {
    this._180dHourlyInterestRate = _180dHourlyInterestRate;
  }


  public SapiV1LoanLoanableDataGet200ResponseRowsInner _180dDailyInterestRate(String _180dDailyInterestRate) {
    
    this._180dDailyInterestRate = _180dDailyInterestRate;
    return this;
  }

   /**
   * Get _180dDailyInterestRate
   * @return _180dDailyInterestRate
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.000151", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_180D_DAILY_INTEREST_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String get180dDailyInterestRate() {
    return _180dDailyInterestRate;
  }


  @JsonProperty(JSON_PROPERTY_180D_DAILY_INTEREST_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void set180dDailyInterestRate(String _180dDailyInterestRate) {
    this._180dDailyInterestRate = _180dDailyInterestRate;
  }


  public SapiV1LoanLoanableDataGet200ResponseRowsInner minLimit(String minLimit) {
    
    this.minLimit = minLimit;
    return this;
  }

   /**
   * Get minLimit
   * @return minLimit
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "100", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_MIN_LIMIT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMinLimit() {
    return minLimit;
  }


  @JsonProperty(JSON_PROPERTY_MIN_LIMIT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMinLimit(String minLimit) {
    this.minLimit = minLimit;
  }


  public SapiV1LoanLoanableDataGet200ResponseRowsInner maxLimit(String maxLimit) {
    
    this.maxLimit = maxLimit;
    return this;
  }

   /**
   * Get maxLimit
   * @return maxLimit
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1000000", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_MAX_LIMIT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMaxLimit() {
    return maxLimit;
  }


  @JsonProperty(JSON_PROPERTY_MAX_LIMIT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMaxLimit(String maxLimit) {
    this.maxLimit = maxLimit;
  }


  public SapiV1LoanLoanableDataGet200ResponseRowsInner vipLevel(Integer vipLevel) {
    
    this.vipLevel = vipLevel;
    return this;
  }

   /**
   * Get vipLevel
   * @return vipLevel
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_VIP_LEVEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getVipLevel() {
    return vipLevel;
  }


  @JsonProperty(JSON_PROPERTY_VIP_LEVEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVipLevel(Integer vipLevel) {
    this.vipLevel = vipLevel;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SapiV1LoanLoanableDataGet200ResponseRowsInner sapiV1LoanLoanableDataGet200ResponseRowsInner = (SapiV1LoanLoanableDataGet200ResponseRowsInner) o;
    return Objects.equals(this.loanCoin, sapiV1LoanLoanableDataGet200ResponseRowsInner.loanCoin) &&
        Objects.equals(this._7dHourlyInterestRate, sapiV1LoanLoanableDataGet200ResponseRowsInner._7dHourlyInterestRate) &&
        Objects.equals(this._7dDailyInterestRate, sapiV1LoanLoanableDataGet200ResponseRowsInner._7dDailyInterestRate) &&
        Objects.equals(this._14dHourlyInterestRate, sapiV1LoanLoanableDataGet200ResponseRowsInner._14dHourlyInterestRate) &&
        Objects.equals(this._14dDailyInterestRate, sapiV1LoanLoanableDataGet200ResponseRowsInner._14dDailyInterestRate) &&
        Objects.equals(this._30dHourlyInterestRate, sapiV1LoanLoanableDataGet200ResponseRowsInner._30dHourlyInterestRate) &&
        Objects.equals(this._30dDailyInterestRate, sapiV1LoanLoanableDataGet200ResponseRowsInner._30dDailyInterestRate) &&
        Objects.equals(this._90dHourlyInterestRate, sapiV1LoanLoanableDataGet200ResponseRowsInner._90dHourlyInterestRate) &&
        Objects.equals(this._90dDailyInterestRate, sapiV1LoanLoanableDataGet200ResponseRowsInner._90dDailyInterestRate) &&
        Objects.equals(this._180dHourlyInterestRate, sapiV1LoanLoanableDataGet200ResponseRowsInner._180dHourlyInterestRate) &&
        Objects.equals(this._180dDailyInterestRate, sapiV1LoanLoanableDataGet200ResponseRowsInner._180dDailyInterestRate) &&
        Objects.equals(this.minLimit, sapiV1LoanLoanableDataGet200ResponseRowsInner.minLimit) &&
        Objects.equals(this.maxLimit, sapiV1LoanLoanableDataGet200ResponseRowsInner.maxLimit) &&
        Objects.equals(this.vipLevel, sapiV1LoanLoanableDataGet200ResponseRowsInner.vipLevel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loanCoin, _7dHourlyInterestRate, _7dDailyInterestRate, _14dHourlyInterestRate, _14dDailyInterestRate, _30dHourlyInterestRate, _30dDailyInterestRate, _90dHourlyInterestRate, _90dDailyInterestRate, _180dHourlyInterestRate, _180dDailyInterestRate, minLimit, maxLimit, vipLevel);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SapiV1LoanLoanableDataGet200ResponseRowsInner {\n");
    sb.append("    loanCoin: ").append(toIndentedString(loanCoin)).append("\n");
    sb.append("    _7dHourlyInterestRate: ").append(toIndentedString(_7dHourlyInterestRate)).append("\n");
    sb.append("    _7dDailyInterestRate: ").append(toIndentedString(_7dDailyInterestRate)).append("\n");
    sb.append("    _14dHourlyInterestRate: ").append(toIndentedString(_14dHourlyInterestRate)).append("\n");
    sb.append("    _14dDailyInterestRate: ").append(toIndentedString(_14dDailyInterestRate)).append("\n");
    sb.append("    _30dHourlyInterestRate: ").append(toIndentedString(_30dHourlyInterestRate)).append("\n");
    sb.append("    _30dDailyInterestRate: ").append(toIndentedString(_30dDailyInterestRate)).append("\n");
    sb.append("    _90dHourlyInterestRate: ").append(toIndentedString(_90dHourlyInterestRate)).append("\n");
    sb.append("    _90dDailyInterestRate: ").append(toIndentedString(_90dDailyInterestRate)).append("\n");
    sb.append("    _180dHourlyInterestRate: ").append(toIndentedString(_180dHourlyInterestRate)).append("\n");
    sb.append("    _180dDailyInterestRate: ").append(toIndentedString(_180dDailyInterestRate)).append("\n");
    sb.append("    minLimit: ").append(toIndentedString(minLimit)).append("\n");
    sb.append("    maxLimit: ").append(toIndentedString(maxLimit)).append("\n");
    sb.append("    vipLevel: ").append(toIndentedString(vipLevel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

