/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SapiV1NftHistoryDepositGet200ResponseListInner
 */
@JsonPropertyOrder({
  SapiV1NftHistoryDepositGet200ResponseListInner.JSON_PROPERTY_NETWORK,
  SapiV1NftHistoryDepositGet200ResponseListInner.JSON_PROPERTY_TX_I_D,
  SapiV1NftHistoryDepositGet200ResponseListInner.JSON_PROPERTY_CONTRACT_ADRRESS,
  SapiV1NftHistoryDepositGet200ResponseListInner.JSON_PROPERTY_TOKEN_ID,
  SapiV1NftHistoryDepositGet200ResponseListInner.JSON_PROPERTY_TIMESTAMP
})
@JsonTypeName("_sapi_v1_nft_history_deposit_get_200_response_list_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SapiV1NftHistoryDepositGet200ResponseListInner {
  public static final String JSON_PROPERTY_NETWORK = "network";
  private String network;

  public static final String JSON_PROPERTY_TX_I_D = "txID";
  private Integer txID;

  public static final String JSON_PROPERTY_CONTRACT_ADRRESS = "contractAdrress";
  private String contractAdrress;

  public static final String JSON_PROPERTY_TOKEN_ID = "tokenId";
  private String tokenId;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  private Long timestamp;

  public SapiV1NftHistoryDepositGet200ResponseListInner() {
  }

  public SapiV1NftHistoryDepositGet200ResponseListInner network(String network) {
    
    this.network = network;
    return this;
  }

   /**
   * Get network
   * @return network
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "ETH", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_NETWORK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNetwork() {
    return network;
  }


  @JsonProperty(JSON_PROPERTY_NETWORK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNetwork(String network) {
    this.network = network;
  }


  public SapiV1NftHistoryDepositGet200ResponseListInner txID(Integer txID) {
    
    this.txID = txID;
    return this;
  }

   /**
   * Get txID
   * @return txID
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TX_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTxID() {
    return txID;
  }


  @JsonProperty(JSON_PROPERTY_TX_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTxID(Integer txID) {
    this.txID = txID;
  }


  public SapiV1NftHistoryDepositGet200ResponseListInner contractAdrress(String contractAdrress) {
    
    this.contractAdrress = contractAdrress;
    return this;
  }

   /**
   * Get contractAdrress
   * @return contractAdrress
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0xe507c961ee127d4439977a61af39c34eafee0dc6", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CONTRACT_ADRRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getContractAdrress() {
    return contractAdrress;
  }


  @JsonProperty(JSON_PROPERTY_CONTRACT_ADRRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContractAdrress(String contractAdrress) {
    this.contractAdrress = contractAdrress;
  }


  public SapiV1NftHistoryDepositGet200ResponseListInner tokenId(String tokenId) {
    
    this.tokenId = tokenId;
    return this;
  }

   /**
   * Get tokenId
   * @return tokenId
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "10014", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TOKEN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTokenId() {
    return tokenId;
  }


  @JsonProperty(JSON_PROPERTY_TOKEN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTokenId(String tokenId) {
    this.tokenId = tokenId;
  }


  public SapiV1NftHistoryDepositGet200ResponseListInner timestamp(Long timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1629986047000", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getTimestamp() {
    return timestamp;
  }


  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTimestamp(Long timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SapiV1NftHistoryDepositGet200ResponseListInner sapiV1NftHistoryDepositGet200ResponseListInner = (SapiV1NftHistoryDepositGet200ResponseListInner) o;
    return Objects.equals(this.network, sapiV1NftHistoryDepositGet200ResponseListInner.network) &&
        Objects.equals(this.txID, sapiV1NftHistoryDepositGet200ResponseListInner.txID) &&
        Objects.equals(this.contractAdrress, sapiV1NftHistoryDepositGet200ResponseListInner.contractAdrress) &&
        Objects.equals(this.tokenId, sapiV1NftHistoryDepositGet200ResponseListInner.tokenId) &&
        Objects.equals(this.timestamp, sapiV1NftHistoryDepositGet200ResponseListInner.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(network, txID, contractAdrress, tokenId, timestamp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SapiV1NftHistoryDepositGet200ResponseListInner {\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    txID: ").append(toIndentedString(txID)).append("\n");
    sb.append("    contractAdrress: ").append(toIndentedString(contractAdrress)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

