/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.olbaid.binance.service.model.SapiV1LendingAutoInvestPlanListGet200ResponsePlanInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SapiV1LendingAutoInvestPlanListGet200Response
 */
@JsonPropertyOrder({
  SapiV1LendingAutoInvestPlanListGet200Response.JSON_PROPERTY_PLAN_VALUE_IN_U_S_D,
  SapiV1LendingAutoInvestPlanListGet200Response.JSON_PROPERTY_PLAN_VALUE_IN_B_T_C,
  SapiV1LendingAutoInvestPlanListGet200Response.JSON_PROPERTY_PNL_IN_U_S_D,
  SapiV1LendingAutoInvestPlanListGet200Response.JSON_PROPERTY_ROI,
  SapiV1LendingAutoInvestPlanListGet200Response.JSON_PROPERTY_PLAN
})
@JsonTypeName("_sapi_v1_lending_auto_invest_plan_list_get_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SapiV1LendingAutoInvestPlanListGet200Response {
  public static final String JSON_PROPERTY_PLAN_VALUE_IN_U_S_D = "planValueInUSD";
  private String planValueInUSD;

  public static final String JSON_PROPERTY_PLAN_VALUE_IN_B_T_C = "planValueInBTC";
  private String planValueInBTC;

  public static final String JSON_PROPERTY_PNL_IN_U_S_D = "pnlInUSD";
  private String pnlInUSD;

  public static final String JSON_PROPERTY_ROI = "roi";
  private String roi;

  public static final String JSON_PROPERTY_PLAN = "plan";
  private List<SapiV1LendingAutoInvestPlanListGet200ResponsePlanInner> plan = new ArrayList<>();

  public SapiV1LendingAutoInvestPlanListGet200Response() {
  }

  public SapiV1LendingAutoInvestPlanListGet200Response planValueInUSD(String planValueInUSD) {
    
    this.planValueInUSD = planValueInUSD;
    return this;
  }

   /**
   * Get planValueInUSD
   * @return planValueInUSD
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "123", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PLAN_VALUE_IN_U_S_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPlanValueInUSD() {
    return planValueInUSD;
  }


  @JsonProperty(JSON_PROPERTY_PLAN_VALUE_IN_U_S_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPlanValueInUSD(String planValueInUSD) {
    this.planValueInUSD = planValueInUSD;
  }


  public SapiV1LendingAutoInvestPlanListGet200Response planValueInBTC(String planValueInBTC) {
    
    this.planValueInBTC = planValueInBTC;
    return this;
  }

   /**
   * Get planValueInBTC
   * @return planValueInBTC
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.1", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PLAN_VALUE_IN_B_T_C)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPlanValueInBTC() {
    return planValueInBTC;
  }


  @JsonProperty(JSON_PROPERTY_PLAN_VALUE_IN_B_T_C)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPlanValueInBTC(String planValueInBTC) {
    this.planValueInBTC = planValueInBTC;
  }


  public SapiV1LendingAutoInvestPlanListGet200Response pnlInUSD(String pnlInUSD) {
    
    this.pnlInUSD = pnlInUSD;
    return this;
  }

   /**
   * Get pnlInUSD
   * @return pnlInUSD
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "120", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PNL_IN_U_S_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPnlInUSD() {
    return pnlInUSD;
  }


  @JsonProperty(JSON_PROPERTY_PNL_IN_U_S_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPnlInUSD(String pnlInUSD) {
    this.pnlInUSD = pnlInUSD;
  }


  public SapiV1LendingAutoInvestPlanListGet200Response roi(String roi) {
    
    this.roi = roi;
    return this;
  }

   /**
   * Get roi
   * @return roi
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "2.3", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ROI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRoi() {
    return roi;
  }


  @JsonProperty(JSON_PROPERTY_ROI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRoi(String roi) {
    this.roi = roi;
  }


  public SapiV1LendingAutoInvestPlanListGet200Response plan(List<SapiV1LendingAutoInvestPlanListGet200ResponsePlanInner> plan) {
    
    this.plan = plan;
    return this;
  }

  public SapiV1LendingAutoInvestPlanListGet200Response addPlanItem(SapiV1LendingAutoInvestPlanListGet200ResponsePlanInner planItem) {
    this.plan.add(planItem);
    return this;
  }

   /**
   * Get plan
   * @return plan
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PLAN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<SapiV1LendingAutoInvestPlanListGet200ResponsePlanInner> getPlan() {
    return plan;
  }


  @JsonProperty(JSON_PROPERTY_PLAN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPlan(List<SapiV1LendingAutoInvestPlanListGet200ResponsePlanInner> plan) {
    this.plan = plan;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SapiV1LendingAutoInvestPlanListGet200Response sapiV1LendingAutoInvestPlanListGet200Response = (SapiV1LendingAutoInvestPlanListGet200Response) o;
    return Objects.equals(this.planValueInUSD, sapiV1LendingAutoInvestPlanListGet200Response.planValueInUSD) &&
        Objects.equals(this.planValueInBTC, sapiV1LendingAutoInvestPlanListGet200Response.planValueInBTC) &&
        Objects.equals(this.pnlInUSD, sapiV1LendingAutoInvestPlanListGet200Response.pnlInUSD) &&
        Objects.equals(this.roi, sapiV1LendingAutoInvestPlanListGet200Response.roi) &&
        Objects.equals(this.plan, sapiV1LendingAutoInvestPlanListGet200Response.plan);
  }

  @Override
  public int hashCode() {
    return Objects.hash(planValueInUSD, planValueInBTC, pnlInUSD, roi, plan);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SapiV1LendingAutoInvestPlanListGet200Response {\n");
    sb.append("    planValueInUSD: ").append(toIndentedString(planValueInUSD)).append("\n");
    sb.append("    planValueInBTC: ").append(toIndentedString(planValueInBTC)).append("\n");
    sb.append("    pnlInUSD: ").append(toIndentedString(pnlInUSD)).append("\n");
    sb.append("    roi: ").append(toIndentedString(roi)).append("\n");
    sb.append("    plan: ").append(toIndentedString(plan)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

