/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SapiV1SubAccountFuturesPositionRiskGet200ResponseInner
 */
@JsonPropertyOrder({
  SapiV1SubAccountFuturesPositionRiskGet200ResponseInner.JSON_PROPERTY_ENTRY_PRICE,
  SapiV1SubAccountFuturesPositionRiskGet200ResponseInner.JSON_PROPERTY_LEVERAGE,
  SapiV1SubAccountFuturesPositionRiskGet200ResponseInner.JSON_PROPERTY_MAX_NOTIONAL,
  SapiV1SubAccountFuturesPositionRiskGet200ResponseInner.JSON_PROPERTY_LIQUIDATION_PRICE,
  SapiV1SubAccountFuturesPositionRiskGet200ResponseInner.JSON_PROPERTY_MARK_PRICE,
  SapiV1SubAccountFuturesPositionRiskGet200ResponseInner.JSON_PROPERTY_POSITION_AMOUNT,
  SapiV1SubAccountFuturesPositionRiskGet200ResponseInner.JSON_PROPERTY_SYMBOL,
  SapiV1SubAccountFuturesPositionRiskGet200ResponseInner.JSON_PROPERTY_UNREALIZED_PROFIT
})
@JsonTypeName("_sapi_v1_sub_account_futures_positionRisk_get_200_response_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SapiV1SubAccountFuturesPositionRiskGet200ResponseInner {
  public static final String JSON_PROPERTY_ENTRY_PRICE = "entryPrice";
  private String entryPrice;

  public static final String JSON_PROPERTY_LEVERAGE = "leverage";
  private String leverage;

  public static final String JSON_PROPERTY_MAX_NOTIONAL = "maxNotional";
  private String maxNotional;

  public static final String JSON_PROPERTY_LIQUIDATION_PRICE = "liquidationPrice";
  private String liquidationPrice;

  public static final String JSON_PROPERTY_MARK_PRICE = "markPrice";
  private String markPrice;

  public static final String JSON_PROPERTY_POSITION_AMOUNT = "positionAmount";
  private String positionAmount;

  public static final String JSON_PROPERTY_SYMBOL = "symbol";
  private String symbol;

  public static final String JSON_PROPERTY_UNREALIZED_PROFIT = "unrealizedProfit";
  private String unrealizedProfit;

  public SapiV1SubAccountFuturesPositionRiskGet200ResponseInner() {
  }

  public SapiV1SubAccountFuturesPositionRiskGet200ResponseInner entryPrice(String entryPrice) {
    
    this.entryPrice = entryPrice;
    return this;
  }

   /**
   * Get entryPrice
   * @return entryPrice
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "9975.12000", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ENTRY_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEntryPrice() {
    return entryPrice;
  }


  @JsonProperty(JSON_PROPERTY_ENTRY_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEntryPrice(String entryPrice) {
    this.entryPrice = entryPrice;
  }


  public SapiV1SubAccountFuturesPositionRiskGet200ResponseInner leverage(String leverage) {
    
    this.leverage = leverage;
    return this;
  }

   /**
   * current initial leverage
   * @return leverage
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "50", required = true, value = "current initial leverage")
  @JsonProperty(JSON_PROPERTY_LEVERAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLeverage() {
    return leverage;
  }


  @JsonProperty(JSON_PROPERTY_LEVERAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLeverage(String leverage) {
    this.leverage = leverage;
  }


  public SapiV1SubAccountFuturesPositionRiskGet200ResponseInner maxNotional(String maxNotional) {
    
    this.maxNotional = maxNotional;
    return this;
  }

   /**
   * notional value limit of current initial leverage
   * @return maxNotional
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1000000", required = true, value = "notional value limit of current initial leverage")
  @JsonProperty(JSON_PROPERTY_MAX_NOTIONAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMaxNotional() {
    return maxNotional;
  }


  @JsonProperty(JSON_PROPERTY_MAX_NOTIONAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMaxNotional(String maxNotional) {
    this.maxNotional = maxNotional;
  }


  public SapiV1SubAccountFuturesPositionRiskGet200ResponseInner liquidationPrice(String liquidationPrice) {
    
    this.liquidationPrice = liquidationPrice;
    return this;
  }

   /**
   * Get liquidationPrice
   * @return liquidationPrice
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "7963.54", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LIQUIDATION_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLiquidationPrice() {
    return liquidationPrice;
  }


  @JsonProperty(JSON_PROPERTY_LIQUIDATION_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLiquidationPrice(String liquidationPrice) {
    this.liquidationPrice = liquidationPrice;
  }


  public SapiV1SubAccountFuturesPositionRiskGet200ResponseInner markPrice(String markPrice) {
    
    this.markPrice = markPrice;
    return this;
  }

   /**
   * Get markPrice
   * @return markPrice
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "9973.50770517", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_MARK_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMarkPrice() {
    return markPrice;
  }


  @JsonProperty(JSON_PROPERTY_MARK_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMarkPrice(String markPrice) {
    this.markPrice = markPrice;
  }


  public SapiV1SubAccountFuturesPositionRiskGet200ResponseInner positionAmount(String positionAmount) {
    
    this.positionAmount = positionAmount;
    return this;
  }

   /**
   * Get positionAmount
   * @return positionAmount
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.010", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_POSITION_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPositionAmount() {
    return positionAmount;
  }


  @JsonProperty(JSON_PROPERTY_POSITION_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPositionAmount(String positionAmount) {
    this.positionAmount = positionAmount;
  }


  public SapiV1SubAccountFuturesPositionRiskGet200ResponseInner symbol(String symbol) {
    
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "BTCUSDT", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSymbol() {
    return symbol;
  }


  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }


  public SapiV1SubAccountFuturesPositionRiskGet200ResponseInner unrealizedProfit(String unrealizedProfit) {
    
    this.unrealizedProfit = unrealizedProfit;
    return this;
  }

   /**
   * Get unrealizedProfit
   * @return unrealizedProfit
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "-0.01612295", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_UNREALIZED_PROFIT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUnrealizedProfit() {
    return unrealizedProfit;
  }


  @JsonProperty(JSON_PROPERTY_UNREALIZED_PROFIT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUnrealizedProfit(String unrealizedProfit) {
    this.unrealizedProfit = unrealizedProfit;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SapiV1SubAccountFuturesPositionRiskGet200ResponseInner sapiV1SubAccountFuturesPositionRiskGet200ResponseInner = (SapiV1SubAccountFuturesPositionRiskGet200ResponseInner) o;
    return Objects.equals(this.entryPrice, sapiV1SubAccountFuturesPositionRiskGet200ResponseInner.entryPrice) &&
        Objects.equals(this.leverage, sapiV1SubAccountFuturesPositionRiskGet200ResponseInner.leverage) &&
        Objects.equals(this.maxNotional, sapiV1SubAccountFuturesPositionRiskGet200ResponseInner.maxNotional) &&
        Objects.equals(this.liquidationPrice, sapiV1SubAccountFuturesPositionRiskGet200ResponseInner.liquidationPrice) &&
        Objects.equals(this.markPrice, sapiV1SubAccountFuturesPositionRiskGet200ResponseInner.markPrice) &&
        Objects.equals(this.positionAmount, sapiV1SubAccountFuturesPositionRiskGet200ResponseInner.positionAmount) &&
        Objects.equals(this.symbol, sapiV1SubAccountFuturesPositionRiskGet200ResponseInner.symbol) &&
        Objects.equals(this.unrealizedProfit, sapiV1SubAccountFuturesPositionRiskGet200ResponseInner.unrealizedProfit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entryPrice, leverage, maxNotional, liquidationPrice, markPrice, positionAmount, symbol, unrealizedProfit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SapiV1SubAccountFuturesPositionRiskGet200ResponseInner {\n");
    sb.append("    entryPrice: ").append(toIndentedString(entryPrice)).append("\n");
    sb.append("    leverage: ").append(toIndentedString(leverage)).append("\n");
    sb.append("    maxNotional: ").append(toIndentedString(maxNotional)).append("\n");
    sb.append("    liquidationPrice: ").append(toIndentedString(liquidationPrice)).append("\n");
    sb.append("    markPrice: ").append(toIndentedString(markPrice)).append("\n");
    sb.append("    positionAmount: ").append(toIndentedString(positionAmount)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    unrealizedProfit: ").append(toIndentedString(unrealizedProfit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

