/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.olbaid.binance.service.model.SapiV1MarginCrossMarginCollateralRatioGet200ResponseInnerCollateralsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SapiV1MarginCrossMarginCollateralRatioGet200ResponseInner
 */
@JsonPropertyOrder({
  SapiV1MarginCrossMarginCollateralRatioGet200ResponseInner.JSON_PROPERTY_COLLATERALS,
  SapiV1MarginCrossMarginCollateralRatioGet200ResponseInner.JSON_PROPERTY_ASSET_NAMES
})
@JsonTypeName("_sapi_v1_margin_crossMarginCollateralRatio_get_200_response_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SapiV1MarginCrossMarginCollateralRatioGet200ResponseInner {
  public static final String JSON_PROPERTY_COLLATERALS = "collaterals";
  private List<SapiV1MarginCrossMarginCollateralRatioGet200ResponseInnerCollateralsInner> collaterals = new ArrayList<>();

  public static final String JSON_PROPERTY_ASSET_NAMES = "assetNames";
  private List<String> assetNames = new ArrayList<>();

  public SapiV1MarginCrossMarginCollateralRatioGet200ResponseInner() {
  }

  public SapiV1MarginCrossMarginCollateralRatioGet200ResponseInner collaterals(List<SapiV1MarginCrossMarginCollateralRatioGet200ResponseInnerCollateralsInner> collaterals) {
    
    this.collaterals = collaterals;
    return this;
  }

  public SapiV1MarginCrossMarginCollateralRatioGet200ResponseInner addCollateralsItem(SapiV1MarginCrossMarginCollateralRatioGet200ResponseInnerCollateralsInner collateralsItem) {
    this.collaterals.add(collateralsItem);
    return this;
  }

   /**
   * Get collaterals
   * @return collaterals
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_COLLATERALS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<SapiV1MarginCrossMarginCollateralRatioGet200ResponseInnerCollateralsInner> getCollaterals() {
    return collaterals;
  }


  @JsonProperty(JSON_PROPERTY_COLLATERALS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCollaterals(List<SapiV1MarginCrossMarginCollateralRatioGet200ResponseInnerCollateralsInner> collaterals) {
    this.collaterals = collaterals;
  }


  public SapiV1MarginCrossMarginCollateralRatioGet200ResponseInner assetNames(List<String> assetNames) {
    
    this.assetNames = assetNames;
    return this;
  }

  public SapiV1MarginCrossMarginCollateralRatioGet200ResponseInner addAssetNamesItem(String assetNamesItem) {
    this.assetNames.add(assetNamesItem);
    return this;
  }

   /**
   * Get assetNames
   * @return assetNames
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ASSET_NAMES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getAssetNames() {
    return assetNames;
  }


  @JsonProperty(JSON_PROPERTY_ASSET_NAMES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAssetNames(List<String> assetNames) {
    this.assetNames = assetNames;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SapiV1MarginCrossMarginCollateralRatioGet200ResponseInner sapiV1MarginCrossMarginCollateralRatioGet200ResponseInner = (SapiV1MarginCrossMarginCollateralRatioGet200ResponseInner) o;
    return Objects.equals(this.collaterals, sapiV1MarginCrossMarginCollateralRatioGet200ResponseInner.collaterals) &&
        Objects.equals(this.assetNames, sapiV1MarginCrossMarginCollateralRatioGet200ResponseInner.assetNames);
  }

  @Override
  public int hashCode() {
    return Objects.hash(collaterals, assetNames);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SapiV1MarginCrossMarginCollateralRatioGet200ResponseInner {\n");
    sb.append("    collaterals: ").append(toIndentedString(collaterals)).append("\n");
    sb.append("    assetNames: ").append(toIndentedString(assetNames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

