/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SapiV1SimpleEarnFlexibleHistoryRateHistoryGet200ResponseRowsInner
 */
@JsonPropertyOrder({
  SapiV1SimpleEarnFlexibleHistoryRateHistoryGet200ResponseRowsInner.JSON_PROPERTY_PRODUCT_ID,
  SapiV1SimpleEarnFlexibleHistoryRateHistoryGet200ResponseRowsInner.JSON_PROPERTY_ASSET,
  SapiV1SimpleEarnFlexibleHistoryRateHistoryGet200ResponseRowsInner.JSON_PROPERTY_ANNUAL_PERCENTAGE_RATE,
  SapiV1SimpleEarnFlexibleHistoryRateHistoryGet200ResponseRowsInner.JSON_PROPERTY_TIME
})
@JsonTypeName("_sapi_v1_simple_earn_flexible_history_rateHistory_get_200_response_rows_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SapiV1SimpleEarnFlexibleHistoryRateHistoryGet200ResponseRowsInner {
  public static final String JSON_PROPERTY_PRODUCT_ID = "productId";
  private String productId;

  public static final String JSON_PROPERTY_ASSET = "asset";
  private String asset;

  public static final String JSON_PROPERTY_ANNUAL_PERCENTAGE_RATE = "annualPercentageRate";
  private String annualPercentageRate;

  public static final String JSON_PROPERTY_TIME = "time";
  private Long time;

  public SapiV1SimpleEarnFlexibleHistoryRateHistoryGet200ResponseRowsInner() {
  }

  public SapiV1SimpleEarnFlexibleHistoryRateHistoryGet200ResponseRowsInner productId(String productId) {
    
    this.productId = productId;
    return this;
  }

   /**
   * Get productId
   * @return productId
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "BUSD001", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProductId() {
    return productId;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProductId(String productId) {
    this.productId = productId;
  }


  public SapiV1SimpleEarnFlexibleHistoryRateHistoryGet200ResponseRowsInner asset(String asset) {
    
    this.asset = asset;
    return this;
  }

   /**
   * Get asset
   * @return asset
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "BUSD", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ASSET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAsset() {
    return asset;
  }


  @JsonProperty(JSON_PROPERTY_ASSET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAsset(String asset) {
    this.asset = asset;
  }


  public SapiV1SimpleEarnFlexibleHistoryRateHistoryGet200ResponseRowsInner annualPercentageRate(String annualPercentageRate) {
    
    this.annualPercentageRate = annualPercentageRate;
    return this;
  }

   /**
   * Get annualPercentageRate
   * @return annualPercentageRate
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.00006408", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ANNUAL_PERCENTAGE_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAnnualPercentageRate() {
    return annualPercentageRate;
  }


  @JsonProperty(JSON_PROPERTY_ANNUAL_PERCENTAGE_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAnnualPercentageRate(String annualPercentageRate) {
    this.annualPercentageRate = annualPercentageRate;
  }


  public SapiV1SimpleEarnFlexibleHistoryRateHistoryGet200ResponseRowsInner time(Long time) {
    
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1577233578000", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getTime() {
    return time;
  }


  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTime(Long time) {
    this.time = time;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SapiV1SimpleEarnFlexibleHistoryRateHistoryGet200ResponseRowsInner sapiV1SimpleEarnFlexibleHistoryRateHistoryGet200ResponseRowsInner = (SapiV1SimpleEarnFlexibleHistoryRateHistoryGet200ResponseRowsInner) o;
    return Objects.equals(this.productId, sapiV1SimpleEarnFlexibleHistoryRateHistoryGet200ResponseRowsInner.productId) &&
        Objects.equals(this.asset, sapiV1SimpleEarnFlexibleHistoryRateHistoryGet200ResponseRowsInner.asset) &&
        Objects.equals(this.annualPercentageRate, sapiV1SimpleEarnFlexibleHistoryRateHistoryGet200ResponseRowsInner.annualPercentageRate) &&
        Objects.equals(this.time, sapiV1SimpleEarnFlexibleHistoryRateHistoryGet200ResponseRowsInner.time);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productId, asset, annualPercentageRate, time);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SapiV1SimpleEarnFlexibleHistoryRateHistoryGet200ResponseRowsInner {\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    asset: ").append(toIndentedString(asset)).append("\n");
    sb.append("    annualPercentageRate: ").append(toIndentedString(annualPercentageRate)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

