/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SapiV1SimpleEarnLockedListGet200ResponseRowsInnerQuota
 */
@JsonPropertyOrder({
  SapiV1SimpleEarnLockedListGet200ResponseRowsInnerQuota.JSON_PROPERTY_TOTAL_PERSONAL_QUOTA,
  SapiV1SimpleEarnLockedListGet200ResponseRowsInnerQuota.JSON_PROPERTY_MINIMUM
})
@JsonTypeName("_sapi_v1_simple_earn_locked_list_get_200_response_rows_inner_quota")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SapiV1SimpleEarnLockedListGet200ResponseRowsInnerQuota {
  public static final String JSON_PROPERTY_TOTAL_PERSONAL_QUOTA = "totalPersonalQuota";
  private String totalPersonalQuota;

  public static final String JSON_PROPERTY_MINIMUM = "minimum";
  private String minimum;

  public SapiV1SimpleEarnLockedListGet200ResponseRowsInnerQuota() {
  }

  public SapiV1SimpleEarnLockedListGet200ResponseRowsInnerQuota totalPersonalQuota(String totalPersonalQuota) {
    
    this.totalPersonalQuota = totalPersonalQuota;
    return this;
  }

   /**
   * Get totalPersonalQuota
   * @return totalPersonalQuota
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "2", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_PERSONAL_QUOTA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTotalPersonalQuota() {
    return totalPersonalQuota;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_PERSONAL_QUOTA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalPersonalQuota(String totalPersonalQuota) {
    this.totalPersonalQuota = totalPersonalQuota;
  }


  public SapiV1SimpleEarnLockedListGet200ResponseRowsInnerQuota minimum(String minimum) {
    
    this.minimum = minimum;
    return this;
  }

   /**
   * Get minimum
   * @return minimum
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.001", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_MINIMUM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMinimum() {
    return minimum;
  }


  @JsonProperty(JSON_PROPERTY_MINIMUM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMinimum(String minimum) {
    this.minimum = minimum;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SapiV1SimpleEarnLockedListGet200ResponseRowsInnerQuota sapiV1SimpleEarnLockedListGet200ResponseRowsInnerQuota = (SapiV1SimpleEarnLockedListGet200ResponseRowsInnerQuota) o;
    return Objects.equals(this.totalPersonalQuota, sapiV1SimpleEarnLockedListGet200ResponseRowsInnerQuota.totalPersonalQuota) &&
        Objects.equals(this.minimum, sapiV1SimpleEarnLockedListGet200ResponseRowsInnerQuota.minimum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalPersonalQuota, minimum);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SapiV1SimpleEarnLockedListGet200ResponseRowsInnerQuota {\n");
    sb.append("    totalPersonalQuota: ").append(toIndentedString(totalPersonalQuota)).append("\n");
    sb.append("    minimum: ").append(toIndentedString(minimum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

