/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SapiV1AlgoSpotNewOrderTwapPost200Response
 */
@JsonPropertyOrder({
  SapiV1AlgoSpotNewOrderTwapPost200Response.JSON_PROPERTY_CLIENT_ALGO_ID,
  SapiV1AlgoSpotNewOrderTwapPost200Response.JSON_PROPERTY_SUCCESS,
  SapiV1AlgoSpotNewOrderTwapPost200Response.JSON_PROPERTY_CODE,
  SapiV1AlgoSpotNewOrderTwapPost200Response.JSON_PROPERTY_MSG
})
@JsonTypeName("_sapi_v1_algo_spot_newOrderTwap_post_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SapiV1AlgoSpotNewOrderTwapPost200Response {
  public static final String JSON_PROPERTY_CLIENT_ALGO_ID = "clientAlgoId";
  private String clientAlgoId;

  public static final String JSON_PROPERTY_SUCCESS = "success";
  private Boolean success;

  public static final String JSON_PROPERTY_CODE = "code";
  private Integer code;

  public static final String JSON_PROPERTY_MSG = "msg";
  private String msg;

  public SapiV1AlgoSpotNewOrderTwapPost200Response() {
  }

  public SapiV1AlgoSpotNewOrderTwapPost200Response clientAlgoId(String clientAlgoId) {
    
    this.clientAlgoId = clientAlgoId;
    return this;
  }

   /**
   * Get clientAlgoId
   * @return clientAlgoId
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "65ce1630101a480b85915d7e11fd5078", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CLIENT_ALGO_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getClientAlgoId() {
    return clientAlgoId;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_ALGO_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClientAlgoId(String clientAlgoId) {
    this.clientAlgoId = clientAlgoId;
  }


  public SapiV1AlgoSpotNewOrderTwapPost200Response success(Boolean success) {
    
    this.success = success;
    return this;
  }

   /**
   * Get success
   * @return success
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "true", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SUCCESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getSuccess() {
    return success;
  }


  @JsonProperty(JSON_PROPERTY_SUCCESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSuccess(Boolean success) {
    this.success = success;
  }


  public SapiV1AlgoSpotNewOrderTwapPost200Response code(Integer code) {
    
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCode(Integer code) {
    this.code = code;
  }


  public SapiV1AlgoSpotNewOrderTwapPost200Response msg(String msg) {
    
    this.msg = msg;
    return this;
  }

   /**
   * Get msg
   * @return msg
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "OK", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_MSG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMsg() {
    return msg;
  }


  @JsonProperty(JSON_PROPERTY_MSG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMsg(String msg) {
    this.msg = msg;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SapiV1AlgoSpotNewOrderTwapPost200Response sapiV1AlgoSpotNewOrderTwapPost200Response = (SapiV1AlgoSpotNewOrderTwapPost200Response) o;
    return Objects.equals(this.clientAlgoId, sapiV1AlgoSpotNewOrderTwapPost200Response.clientAlgoId) &&
        Objects.equals(this.success, sapiV1AlgoSpotNewOrderTwapPost200Response.success) &&
        Objects.equals(this.code, sapiV1AlgoSpotNewOrderTwapPost200Response.code) &&
        Objects.equals(this.msg, sapiV1AlgoSpotNewOrderTwapPost200Response.msg);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientAlgoId, success, code, msg);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SapiV1AlgoSpotNewOrderTwapPost200Response {\n");
    sb.append("    clientAlgoId: ").append(toIndentedString(clientAlgoId)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    msg: ").append(toIndentedString(msg)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

