/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.olbaid.binance.service.model.SapiV1RebateTaxQueryGet200ResponseDataDataInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SapiV1RebateTaxQueryGet200ResponseData
 */
@JsonPropertyOrder({
  SapiV1RebateTaxQueryGet200ResponseData.JSON_PROPERTY_PAGE,
  SapiV1RebateTaxQueryGet200ResponseData.JSON_PROPERTY_TOTAL_RECORDS,
  SapiV1RebateTaxQueryGet200ResponseData.JSON_PROPERTY_TOTAL_PAGE_NUM,
  SapiV1RebateTaxQueryGet200ResponseData.JSON_PROPERTY_DATA
})
@JsonTypeName("_sapi_v1_rebate_taxQuery_get_200_response_data")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SapiV1RebateTaxQueryGet200ResponseData {
  public static final String JSON_PROPERTY_PAGE = "page";
  private Integer page;

  public static final String JSON_PROPERTY_TOTAL_RECORDS = "totalRecords";
  private Integer totalRecords;

  public static final String JSON_PROPERTY_TOTAL_PAGE_NUM = "totalPageNum";
  private Integer totalPageNum;

  public static final String JSON_PROPERTY_DATA = "data";
  private List<SapiV1RebateTaxQueryGet200ResponseDataDataInner> data = new ArrayList<>();

  public SapiV1RebateTaxQueryGet200ResponseData() {
  }

  public SapiV1RebateTaxQueryGet200ResponseData page(Integer page) {
    
    this.page = page;
    return this;
  }

   /**
   * Get page
   * @return page
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getPage() {
    return page;
  }


  @JsonProperty(JSON_PROPERTY_PAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPage(Integer page) {
    this.page = page;
  }


  public SapiV1RebateTaxQueryGet200ResponseData totalRecords(Integer totalRecords) {
    
    this.totalRecords = totalRecords;
    return this;
  }

   /**
   * Get totalRecords
   * @return totalRecords
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "2", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_RECORDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTotalRecords() {
    return totalRecords;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_RECORDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalRecords(Integer totalRecords) {
    this.totalRecords = totalRecords;
  }


  public SapiV1RebateTaxQueryGet200ResponseData totalPageNum(Integer totalPageNum) {
    
    this.totalPageNum = totalPageNum;
    return this;
  }

   /**
   * Get totalPageNum
   * @return totalPageNum
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_PAGE_NUM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTotalPageNum() {
    return totalPageNum;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_PAGE_NUM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalPageNum(Integer totalPageNum) {
    this.totalPageNum = totalPageNum;
  }


  public SapiV1RebateTaxQueryGet200ResponseData data(List<SapiV1RebateTaxQueryGet200ResponseDataDataInner> data) {
    
    this.data = data;
    return this;
  }

  public SapiV1RebateTaxQueryGet200ResponseData addDataItem(SapiV1RebateTaxQueryGet200ResponseDataDataInner dataItem) {
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<SapiV1RebateTaxQueryGet200ResponseDataDataInner> getData() {
    return data;
  }


  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setData(List<SapiV1RebateTaxQueryGet200ResponseDataDataInner> data) {
    this.data = data;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SapiV1RebateTaxQueryGet200ResponseData sapiV1RebateTaxQueryGet200ResponseData = (SapiV1RebateTaxQueryGet200ResponseData) o;
    return Objects.equals(this.page, sapiV1RebateTaxQueryGet200ResponseData.page) &&
        Objects.equals(this.totalRecords, sapiV1RebateTaxQueryGet200ResponseData.totalRecords) &&
        Objects.equals(this.totalPageNum, sapiV1RebateTaxQueryGet200ResponseData.totalPageNum) &&
        Objects.equals(this.data, sapiV1RebateTaxQueryGet200ResponseData.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(page, totalRecords, totalPageNum, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SapiV1RebateTaxQueryGet200ResponseData {\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    totalRecords: ").append(toIndentedString(totalRecords)).append("\n");
    sb.append("    totalPageNum: ").append(toIndentedString(totalPageNum)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

