/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.olbaid.binance.service.model.SapiV2PortfolioCollateralRateGet200ResponseInnerCollateralInfoInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SapiV2PortfolioCollateralRateGet200ResponseInner
 */
@JsonPropertyOrder({
  SapiV2PortfolioCollateralRateGet200ResponseInner.JSON_PROPERTY_ASSET,
  SapiV2PortfolioCollateralRateGet200ResponseInner.JSON_PROPERTY_COLLATERAL_INFO
})
@JsonTypeName("_sapi_v2_portfolio_collateralRate_get_200_response_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SapiV2PortfolioCollateralRateGet200ResponseInner {
  public static final String JSON_PROPERTY_ASSET = "asset";
  private String asset;

  public static final String JSON_PROPERTY_COLLATERAL_INFO = "collateralInfo";
  private List<SapiV2PortfolioCollateralRateGet200ResponseInnerCollateralInfoInner> collateralInfo = new ArrayList<>();

  public SapiV2PortfolioCollateralRateGet200ResponseInner() {
  }

  public SapiV2PortfolioCollateralRateGet200ResponseInner asset(String asset) {
    
    this.asset = asset;
    return this;
  }

   /**
   * Get asset
   * @return asset
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "BNB", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ASSET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAsset() {
    return asset;
  }


  @JsonProperty(JSON_PROPERTY_ASSET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAsset(String asset) {
    this.asset = asset;
  }


  public SapiV2PortfolioCollateralRateGet200ResponseInner collateralInfo(List<SapiV2PortfolioCollateralRateGet200ResponseInnerCollateralInfoInner> collateralInfo) {
    
    this.collateralInfo = collateralInfo;
    return this;
  }

  public SapiV2PortfolioCollateralRateGet200ResponseInner addCollateralInfoItem(SapiV2PortfolioCollateralRateGet200ResponseInnerCollateralInfoInner collateralInfoItem) {
    this.collateralInfo.add(collateralInfoItem);
    return this;
  }

   /**
   * Get collateralInfo
   * @return collateralInfo
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_COLLATERAL_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<SapiV2PortfolioCollateralRateGet200ResponseInnerCollateralInfoInner> getCollateralInfo() {
    return collateralInfo;
  }


  @JsonProperty(JSON_PROPERTY_COLLATERAL_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCollateralInfo(List<SapiV2PortfolioCollateralRateGet200ResponseInnerCollateralInfoInner> collateralInfo) {
    this.collateralInfo = collateralInfo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SapiV2PortfolioCollateralRateGet200ResponseInner sapiV2PortfolioCollateralRateGet200ResponseInner = (SapiV2PortfolioCollateralRateGet200ResponseInner) o;
    return Objects.equals(this.asset, sapiV2PortfolioCollateralRateGet200ResponseInner.asset) &&
        Objects.equals(this.collateralInfo, sapiV2PortfolioCollateralRateGet200ResponseInner.collateralInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(asset, collateralInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SapiV2PortfolioCollateralRateGet200ResponseInner {\n");
    sb.append("    asset: ").append(toIndentedString(asset)).append("\n");
    sb.append("    collateralInfo: ").append(toIndentedString(collateralInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

