/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SapiV1LoanVipBorrowPost200Response
 */
@JsonPropertyOrder({
  SapiV1LoanVipBorrowPost200Response.JSON_PROPERTY_LOAN_ACCOUNT_ID,
  SapiV1LoanVipBorrowPost200Response.JSON_PROPERTY_REQUEST_ID,
  SapiV1LoanVipBorrowPost200Response.JSON_PROPERTY_LOAN_COIN,
  SapiV1LoanVipBorrowPost200Response.JSON_PROPERTY_IS_FLEXIBLE_RATE,
  SapiV1LoanVipBorrowPost200Response.JSON_PROPERTY_LOAN_AMOUNT,
  SapiV1LoanVipBorrowPost200Response.JSON_PROPERTY_COLLATERAL_ACCOUNT_ID,
  SapiV1LoanVipBorrowPost200Response.JSON_PROPERTY_COLLATERAL_COIN,
  SapiV1LoanVipBorrowPost200Response.JSON_PROPERTY_LOAN_TERM
})
@JsonTypeName("_sapi_v1_loan_vip_borrow_post_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SapiV1LoanVipBorrowPost200Response {
  public static final String JSON_PROPERTY_LOAN_ACCOUNT_ID = "loanAccountId";
  private String loanAccountId;

  public static final String JSON_PROPERTY_REQUEST_ID = "requestId";
  private String requestId;

  public static final String JSON_PROPERTY_LOAN_COIN = "loanCoin";
  private String loanCoin;

  public static final String JSON_PROPERTY_IS_FLEXIBLE_RATE = "isFlexibleRate";
  private String isFlexibleRate;

  public static final String JSON_PROPERTY_LOAN_AMOUNT = "loanAmount";
  private String loanAmount;

  public static final String JSON_PROPERTY_COLLATERAL_ACCOUNT_ID = "collateralAccountId";
  private String collateralAccountId;

  public static final String JSON_PROPERTY_COLLATERAL_COIN = "collateralCoin";
  private String collateralCoin;

  public static final String JSON_PROPERTY_LOAN_TERM = "loanTerm";
  private String loanTerm;

  public SapiV1LoanVipBorrowPost200Response() {
  }

  public SapiV1LoanVipBorrowPost200Response loanAccountId(String loanAccountId) {
    
    this.loanAccountId = loanAccountId;
    return this;
  }

   /**
   * Get loanAccountId
   * @return loanAccountId
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "12345678", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LOAN_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLoanAccountId() {
    return loanAccountId;
  }


  @JsonProperty(JSON_PROPERTY_LOAN_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLoanAccountId(String loanAccountId) {
    this.loanAccountId = loanAccountId;
  }


  public SapiV1LoanVipBorrowPost200Response requestId(String requestId) {
    
    this.requestId = requestId;
    return this;
  }

   /**
   * Get requestId
   * @return requestId
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "12345678", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_REQUEST_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRequestId() {
    return requestId;
  }


  @JsonProperty(JSON_PROPERTY_REQUEST_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }


  public SapiV1LoanVipBorrowPost200Response loanCoin(String loanCoin) {
    
    this.loanCoin = loanCoin;
    return this;
  }

   /**
   * Get loanCoin
   * @return loanCoin
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "BTC", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LOAN_COIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLoanCoin() {
    return loanCoin;
  }


  @JsonProperty(JSON_PROPERTY_LOAN_COIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLoanCoin(String loanCoin) {
    this.loanCoin = loanCoin;
  }


  public SapiV1LoanVipBorrowPost200Response isFlexibleRate(String isFlexibleRate) {
    
    this.isFlexibleRate = isFlexibleRate;
    return this;
  }

   /**
   * Get isFlexibleRate
   * @return isFlexibleRate
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "No", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_IS_FLEXIBLE_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIsFlexibleRate() {
    return isFlexibleRate;
  }


  @JsonProperty(JSON_PROPERTY_IS_FLEXIBLE_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsFlexibleRate(String isFlexibleRate) {
    this.isFlexibleRate = isFlexibleRate;
  }


  public SapiV1LoanVipBorrowPost200Response loanAmount(String loanAmount) {
    
    this.loanAmount = loanAmount;
    return this;
  }

   /**
   * Get loanAmount
   * @return loanAmount
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "100.55", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LOAN_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLoanAmount() {
    return loanAmount;
  }


  @JsonProperty(JSON_PROPERTY_LOAN_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLoanAmount(String loanAmount) {
    this.loanAmount = loanAmount;
  }


  public SapiV1LoanVipBorrowPost200Response collateralAccountId(String collateralAccountId) {
    
    this.collateralAccountId = collateralAccountId;
    return this;
  }

   /**
   * Get collateralAccountId
   * @return collateralAccountId
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "12345678,12345678,12345678", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_COLLATERAL_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCollateralAccountId() {
    return collateralAccountId;
  }


  @JsonProperty(JSON_PROPERTY_COLLATERAL_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCollateralAccountId(String collateralAccountId) {
    this.collateralAccountId = collateralAccountId;
  }


  public SapiV1LoanVipBorrowPost200Response collateralCoin(String collateralCoin) {
    
    this.collateralCoin = collateralCoin;
    return this;
  }

   /**
   * Get collateralCoin
   * @return collateralCoin
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "BUSD,USDT,ETH", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_COLLATERAL_COIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCollateralCoin() {
    return collateralCoin;
  }


  @JsonProperty(JSON_PROPERTY_COLLATERAL_COIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCollateralCoin(String collateralCoin) {
    this.collateralCoin = collateralCoin;
  }


  public SapiV1LoanVipBorrowPost200Response loanTerm(String loanTerm) {
    
    this.loanTerm = loanTerm;
    return this;
  }

   /**
   * Get loanTerm
   * @return loanTerm
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(example = "30", value = "")
  @JsonProperty(JSON_PROPERTY_LOAN_TERM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLoanTerm() {
    return loanTerm;
  }


  @JsonProperty(JSON_PROPERTY_LOAN_TERM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoanTerm(String loanTerm) {
    this.loanTerm = loanTerm;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SapiV1LoanVipBorrowPost200Response sapiV1LoanVipBorrowPost200Response = (SapiV1LoanVipBorrowPost200Response) o;
    return Objects.equals(this.loanAccountId, sapiV1LoanVipBorrowPost200Response.loanAccountId) &&
        Objects.equals(this.requestId, sapiV1LoanVipBorrowPost200Response.requestId) &&
        Objects.equals(this.loanCoin, sapiV1LoanVipBorrowPost200Response.loanCoin) &&
        Objects.equals(this.isFlexibleRate, sapiV1LoanVipBorrowPost200Response.isFlexibleRate) &&
        Objects.equals(this.loanAmount, sapiV1LoanVipBorrowPost200Response.loanAmount) &&
        Objects.equals(this.collateralAccountId, sapiV1LoanVipBorrowPost200Response.collateralAccountId) &&
        Objects.equals(this.collateralCoin, sapiV1LoanVipBorrowPost200Response.collateralCoin) &&
        Objects.equals(this.loanTerm, sapiV1LoanVipBorrowPost200Response.loanTerm);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loanAccountId, requestId, loanCoin, isFlexibleRate, loanAmount, collateralAccountId, collateralCoin, loanTerm);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SapiV1LoanVipBorrowPost200Response {\n");
    sb.append("    loanAccountId: ").append(toIndentedString(loanAccountId)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    loanCoin: ").append(toIndentedString(loanCoin)).append("\n");
    sb.append("    isFlexibleRate: ").append(toIndentedString(isFlexibleRate)).append("\n");
    sb.append("    loanAmount: ").append(toIndentedString(loanAmount)).append("\n");
    sb.append("    collateralAccountId: ").append(toIndentedString(collateralAccountId)).append("\n");
    sb.append("    collateralCoin: ").append(toIndentedString(collateralCoin)).append("\n");
    sb.append("    loanTerm: ").append(toIndentedString(loanTerm)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

