/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner
 */
@JsonPropertyOrder({
  SapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner.JSON_PROPERTY_TIME,
  SapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner.JSON_PROPERTY_FROM_ASSET,
  SapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner.JSON_PROPERTY_FROM_AMOUNT,
  SapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner.JSON_PROPERTY_TO_ASSET,
  SapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner.JSON_PROPERTY_TO_AMOUNT,
  SapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner.JSON_PROPERTY_EXCHANGE_RATE,
  SapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner.JSON_PROPERTY_STATUS
})
@JsonTypeName("_sapi_v1_eth_staking_wbeth_history_unwrapHistory_get_200_response_rows_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner {
  public static final String JSON_PROPERTY_TIME = "time";
  private Long time;

  public static final String JSON_PROPERTY_FROM_ASSET = "fromAsset";
  private String fromAsset;

  public static final String JSON_PROPERTY_FROM_AMOUNT = "fromAmount";
  private String fromAmount;

  public static final String JSON_PROPERTY_TO_ASSET = "toAsset";
  private String toAsset;

  public static final String JSON_PROPERTY_TO_AMOUNT = "toAmount";
  private String toAmount;

  public static final String JSON_PROPERTY_EXCHANGE_RATE = "exchangeRate";
  private String exchangeRate;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public SapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner() {
  }

  public SapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner time(Long time) {
    
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1575018510000", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getTime() {
    return time;
  }


  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTime(Long time) {
    this.time = time;
  }


  public SapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner fromAsset(String fromAsset) {
    
    this.fromAsset = fromAsset;
    return this;
  }

   /**
   * Get fromAsset
   * @return fromAsset
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "WBETH", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_FROM_ASSET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFromAsset() {
    return fromAsset;
  }


  @JsonProperty(JSON_PROPERTY_FROM_ASSET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFromAsset(String fromAsset) {
    this.fromAsset = fromAsset;
  }


  public SapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner fromAmount(String fromAmount) {
    
    this.fromAmount = fromAmount;
    return this;
  }

   /**
   * Get fromAmount
   * @return fromAmount
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "21312.23223", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_FROM_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFromAmount() {
    return fromAmount;
  }


  @JsonProperty(JSON_PROPERTY_FROM_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFromAmount(String fromAmount) {
    this.fromAmount = fromAmount;
  }


  public SapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner toAsset(String toAsset) {
    
    this.toAsset = toAsset;
    return this;
  }

   /**
   * Get toAsset
   * @return toAsset
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "BETH", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TO_ASSET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getToAsset() {
    return toAsset;
  }


  @JsonProperty(JSON_PROPERTY_TO_ASSET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToAsset(String toAsset) {
    this.toAsset = toAsset;
  }


  public SapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner toAmount(String toAmount) {
    
    this.toAmount = toAmount;
    return this;
  }

   /**
   * Get toAmount
   * @return toAmount
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "21312.23223", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TO_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getToAmount() {
    return toAmount;
  }


  @JsonProperty(JSON_PROPERTY_TO_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToAmount(String toAmount) {
    this.toAmount = toAmount;
  }


  public SapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner exchangeRate(String exchangeRate) {
    
    this.exchangeRate = exchangeRate;
    return this;
  }

   /**
   * BETH amount per 1 WBETH
   * @return exchangeRate
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1.01243253", required = true, value = "BETH amount per 1 WBETH")
  @JsonProperty(JSON_PROPERTY_EXCHANGE_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExchangeRate() {
    return exchangeRate;
  }


  @JsonProperty(JSON_PROPERTY_EXCHANGE_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExchangeRate(String exchangeRate) {
    this.exchangeRate = exchangeRate;
  }


  public SapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * PENDING, SUCCESS, FAILED
   * @return status
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "SUCCESS", required = true, value = "PENDING, SUCCESS, FAILED")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner sapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner = (SapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner) o;
    return Objects.equals(this.time, sapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner.time) &&
        Objects.equals(this.fromAsset, sapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner.fromAsset) &&
        Objects.equals(this.fromAmount, sapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner.fromAmount) &&
        Objects.equals(this.toAsset, sapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner.toAsset) &&
        Objects.equals(this.toAmount, sapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner.toAmount) &&
        Objects.equals(this.exchangeRate, sapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner.exchangeRate) &&
        Objects.equals(this.status, sapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(time, fromAsset, fromAmount, toAsset, toAmount, exchangeRate, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SapiV1EthStakingWbethHistoryUnwrapHistoryGet200ResponseRowsInner {\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    fromAsset: ").append(toIndentedString(fromAsset)).append("\n");
    sb.append("    fromAmount: ").append(toIndentedString(fromAmount)).append("\n");
    sb.append("    toAsset: ").append(toIndentedString(toAsset)).append("\n");
    sb.append("    toAmount: ").append(toIndentedString(toAmount)).append("\n");
    sb.append("    exchangeRate: ").append(toIndentedString(exchangeRate)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

