/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SapiV1LoanCollateralDataGet200ResponseRowsInner
 */
@JsonPropertyOrder({
  SapiV1LoanCollateralDataGet200ResponseRowsInner.JSON_PROPERTY_COLLATERAL_COIN,
  SapiV1LoanCollateralDataGet200ResponseRowsInner.JSON_PROPERTY_INITIAL_L_T_V,
  SapiV1LoanCollateralDataGet200ResponseRowsInner.JSON_PROPERTY_MARGIN_CALL_L_T_V,
  SapiV1LoanCollateralDataGet200ResponseRowsInner.JSON_PROPERTY_LIQUIDATION_L_T_V,
  SapiV1LoanCollateralDataGet200ResponseRowsInner.JSON_PROPERTY_MAX_LIMIT,
  SapiV1LoanCollateralDataGet200ResponseRowsInner.JSON_PROPERTY_VIP_LEVEL
})
@JsonTypeName("_sapi_v1_loan_collateral_data_get_200_response_rows_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SapiV1LoanCollateralDataGet200ResponseRowsInner {
  public static final String JSON_PROPERTY_COLLATERAL_COIN = "collateralCoin";
  private String collateralCoin;

  public static final String JSON_PROPERTY_INITIAL_L_T_V = "initialLTV";
  private String initialLTV;

  public static final String JSON_PROPERTY_MARGIN_CALL_L_T_V = "marginCallLTV";
  private String marginCallLTV;

  public static final String JSON_PROPERTY_LIQUIDATION_L_T_V = "liquidationLTV";
  private String liquidationLTV;

  public static final String JSON_PROPERTY_MAX_LIMIT = "maxLimit";
  private String maxLimit;

  public static final String JSON_PROPERTY_VIP_LEVEL = "vipLevel";
  private Integer vipLevel;

  public SapiV1LoanCollateralDataGet200ResponseRowsInner() {
  }

  public SapiV1LoanCollateralDataGet200ResponseRowsInner collateralCoin(String collateralCoin) {
    
    this.collateralCoin = collateralCoin;
    return this;
  }

   /**
   * Get collateralCoin
   * @return collateralCoin
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "BNB", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_COLLATERAL_COIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCollateralCoin() {
    return collateralCoin;
  }


  @JsonProperty(JSON_PROPERTY_COLLATERAL_COIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCollateralCoin(String collateralCoin) {
    this.collateralCoin = collateralCoin;
  }


  public SapiV1LoanCollateralDataGet200ResponseRowsInner initialLTV(String initialLTV) {
    
    this.initialLTV = initialLTV;
    return this;
  }

   /**
   * Get initialLTV
   * @return initialLTV
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.65", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_INITIAL_L_T_V)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getInitialLTV() {
    return initialLTV;
  }


  @JsonProperty(JSON_PROPERTY_INITIAL_L_T_V)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInitialLTV(String initialLTV) {
    this.initialLTV = initialLTV;
  }


  public SapiV1LoanCollateralDataGet200ResponseRowsInner marginCallLTV(String marginCallLTV) {
    
    this.marginCallLTV = marginCallLTV;
    return this;
  }

   /**
   * Get marginCallLTV
   * @return marginCallLTV
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.75", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_MARGIN_CALL_L_T_V)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMarginCallLTV() {
    return marginCallLTV;
  }


  @JsonProperty(JSON_PROPERTY_MARGIN_CALL_L_T_V)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMarginCallLTV(String marginCallLTV) {
    this.marginCallLTV = marginCallLTV;
  }


  public SapiV1LoanCollateralDataGet200ResponseRowsInner liquidationLTV(String liquidationLTV) {
    
    this.liquidationLTV = liquidationLTV;
    return this;
  }

   /**
   * Get liquidationLTV
   * @return liquidationLTV
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.83", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LIQUIDATION_L_T_V)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLiquidationLTV() {
    return liquidationLTV;
  }


  @JsonProperty(JSON_PROPERTY_LIQUIDATION_L_T_V)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLiquidationLTV(String liquidationLTV) {
    this.liquidationLTV = liquidationLTV;
  }


  public SapiV1LoanCollateralDataGet200ResponseRowsInner maxLimit(String maxLimit) {
    
    this.maxLimit = maxLimit;
    return this;
  }

   /**
   * Get maxLimit
   * @return maxLimit
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1000000", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_MAX_LIMIT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMaxLimit() {
    return maxLimit;
  }


  @JsonProperty(JSON_PROPERTY_MAX_LIMIT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMaxLimit(String maxLimit) {
    this.maxLimit = maxLimit;
  }


  public SapiV1LoanCollateralDataGet200ResponseRowsInner vipLevel(Integer vipLevel) {
    
    this.vipLevel = vipLevel;
    return this;
  }

   /**
   * Get vipLevel
   * @return vipLevel
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_VIP_LEVEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getVipLevel() {
    return vipLevel;
  }


  @JsonProperty(JSON_PROPERTY_VIP_LEVEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVipLevel(Integer vipLevel) {
    this.vipLevel = vipLevel;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SapiV1LoanCollateralDataGet200ResponseRowsInner sapiV1LoanCollateralDataGet200ResponseRowsInner = (SapiV1LoanCollateralDataGet200ResponseRowsInner) o;
    return Objects.equals(this.collateralCoin, sapiV1LoanCollateralDataGet200ResponseRowsInner.collateralCoin) &&
        Objects.equals(this.initialLTV, sapiV1LoanCollateralDataGet200ResponseRowsInner.initialLTV) &&
        Objects.equals(this.marginCallLTV, sapiV1LoanCollateralDataGet200ResponseRowsInner.marginCallLTV) &&
        Objects.equals(this.liquidationLTV, sapiV1LoanCollateralDataGet200ResponseRowsInner.liquidationLTV) &&
        Objects.equals(this.maxLimit, sapiV1LoanCollateralDataGet200ResponseRowsInner.maxLimit) &&
        Objects.equals(this.vipLevel, sapiV1LoanCollateralDataGet200ResponseRowsInner.vipLevel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(collateralCoin, initialLTV, marginCallLTV, liquidationLTV, maxLimit, vipLevel);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SapiV1LoanCollateralDataGet200ResponseRowsInner {\n");
    sb.append("    collateralCoin: ").append(toIndentedString(collateralCoin)).append("\n");
    sb.append("    initialLTV: ").append(toIndentedString(initialLTV)).append("\n");
    sb.append("    marginCallLTV: ").append(toIndentedString(marginCallLTV)).append("\n");
    sb.append("    liquidationLTV: ").append(toIndentedString(liquidationLTV)).append("\n");
    sb.append("    maxLimit: ").append(toIndentedString(maxLimit)).append("\n");
    sb.append("    vipLevel: ").append(toIndentedString(vipLevel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

