/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SapiV1MiningPubCoinListGet200ResponseDataInner
 */
@JsonPropertyOrder({
  SapiV1MiningPubCoinListGet200ResponseDataInner.JSON_PROPERTY_COIN_NAME,
  SapiV1MiningPubCoinListGet200ResponseDataInner.JSON_PROPERTY_COIN_ID,
  SapiV1MiningPubCoinListGet200ResponseDataInner.JSON_PROPERTY_POOL_INDEX,
  SapiV1MiningPubCoinListGet200ResponseDataInner.JSON_PROPERTY_ALGO_ID,
  SapiV1MiningPubCoinListGet200ResponseDataInner.JSON_PROPERTY_ALGO_NAME
})
@JsonTypeName("_sapi_v1_mining_pub_coinList_get_200_response_data_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SapiV1MiningPubCoinListGet200ResponseDataInner {
  public static final String JSON_PROPERTY_COIN_NAME = "coinName";
  private String coinName;

  public static final String JSON_PROPERTY_COIN_ID = "coinId";
  private Long coinId;

  public static final String JSON_PROPERTY_POOL_INDEX = "poolIndex";
  private Long poolIndex;

  public static final String JSON_PROPERTY_ALGO_ID = "algoId";
  private Long algoId;

  public static final String JSON_PROPERTY_ALGO_NAME = "algoName";
  private String algoName;

  public SapiV1MiningPubCoinListGet200ResponseDataInner() {
  }

  public SapiV1MiningPubCoinListGet200ResponseDataInner coinName(String coinName) {
    
    this.coinName = coinName;
    return this;
  }

   /**
   * Get coinName
   * @return coinName
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "BTC", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_COIN_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCoinName() {
    return coinName;
  }


  @JsonProperty(JSON_PROPERTY_COIN_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCoinName(String coinName) {
    this.coinName = coinName;
  }


  public SapiV1MiningPubCoinListGet200ResponseDataInner coinId(Long coinId) {
    
    this.coinId = coinId;
    return this;
  }

   /**
   * Get coinId
   * @return coinId
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_COIN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getCoinId() {
    return coinId;
  }


  @JsonProperty(JSON_PROPERTY_COIN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCoinId(Long coinId) {
    this.coinId = coinId;
  }


  public SapiV1MiningPubCoinListGet200ResponseDataInner poolIndex(Long poolIndex) {
    
    this.poolIndex = poolIndex;
    return this;
  }

   /**
   * Get poolIndex
   * @return poolIndex
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_POOL_INDEX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getPoolIndex() {
    return poolIndex;
  }


  @JsonProperty(JSON_PROPERTY_POOL_INDEX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPoolIndex(Long poolIndex) {
    this.poolIndex = poolIndex;
  }


  public SapiV1MiningPubCoinListGet200ResponseDataInner algoId(Long algoId) {
    
    this.algoId = algoId;
    return this;
  }

   /**
   * Get algoId
   * @return algoId
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ALGO_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getAlgoId() {
    return algoId;
  }


  @JsonProperty(JSON_PROPERTY_ALGO_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAlgoId(Long algoId) {
    this.algoId = algoId;
  }


  public SapiV1MiningPubCoinListGet200ResponseDataInner algoName(String algoName) {
    
    this.algoName = algoName;
    return this;
  }

   /**
   * Get algoName
   * @return algoName
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "sha256", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ALGO_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAlgoName() {
    return algoName;
  }


  @JsonProperty(JSON_PROPERTY_ALGO_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAlgoName(String algoName) {
    this.algoName = algoName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SapiV1MiningPubCoinListGet200ResponseDataInner sapiV1MiningPubCoinListGet200ResponseDataInner = (SapiV1MiningPubCoinListGet200ResponseDataInner) o;
    return Objects.equals(this.coinName, sapiV1MiningPubCoinListGet200ResponseDataInner.coinName) &&
        Objects.equals(this.coinId, sapiV1MiningPubCoinListGet200ResponseDataInner.coinId) &&
        Objects.equals(this.poolIndex, sapiV1MiningPubCoinListGet200ResponseDataInner.poolIndex) &&
        Objects.equals(this.algoId, sapiV1MiningPubCoinListGet200ResponseDataInner.algoId) &&
        Objects.equals(this.algoName, sapiV1MiningPubCoinListGet200ResponseDataInner.algoName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(coinName, coinId, poolIndex, algoId, algoName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SapiV1MiningPubCoinListGet200ResponseDataInner {\n");
    sb.append("    coinName: ").append(toIndentedString(coinName)).append("\n");
    sb.append("    coinId: ").append(toIndentedString(coinId)).append("\n");
    sb.append("    poolIndex: ").append(toIndentedString(poolIndex)).append("\n");
    sb.append("    algoId: ").append(toIndentedString(algoId)).append("\n");
    sb.append("    algoName: ").append(toIndentedString(algoName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

