/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SapiV1CapitalDepositAddressListGet200ResponseInner
 */
@JsonPropertyOrder({
  SapiV1CapitalDepositAddressListGet200ResponseInner.JSON_PROPERTY_COIN,
  SapiV1CapitalDepositAddressListGet200ResponseInner.JSON_PROPERTY_ADDRESS,
  SapiV1CapitalDepositAddressListGet200ResponseInner.JSON_PROPERTY_IS_DEFAULT
})
@JsonTypeName("_sapi_v1_capital_deposit_address_list_get_200_response_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SapiV1CapitalDepositAddressListGet200ResponseInner {
  public static final String JSON_PROPERTY_COIN = "coin";
  private String coin;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  private String address;

  public static final String JSON_PROPERTY_IS_DEFAULT = "isDefault";
  private Integer isDefault;

  public SapiV1CapitalDepositAddressListGet200ResponseInner() {
  }

  public SapiV1CapitalDepositAddressListGet200ResponseInner coin(String coin) {
    
    this.coin = coin;
    return this;
  }

   /**
   * Get coin
   * @return coin
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "ETH", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_COIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCoin() {
    return coin;
  }


  @JsonProperty(JSON_PROPERTY_COIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCoin(String coin) {
    this.coin = coin;
  }


  public SapiV1CapitalDepositAddressListGet200ResponseInner address(String address) {
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0xD316E95Fd9E8E237Cb11f8200Babbc5D8D177BA4", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAddress(String address) {
    this.address = address;
  }


  public SapiV1CapitalDepositAddressListGet200ResponseInner isDefault(Integer isDefault) {
    
    this.isDefault = isDefault;
    return this;
  }

   /**
   * Get isDefault
   * @return isDefault
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_IS_DEFAULT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getIsDefault() {
    return isDefault;
  }


  @JsonProperty(JSON_PROPERTY_IS_DEFAULT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsDefault(Integer isDefault) {
    this.isDefault = isDefault;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SapiV1CapitalDepositAddressListGet200ResponseInner sapiV1CapitalDepositAddressListGet200ResponseInner = (SapiV1CapitalDepositAddressListGet200ResponseInner) o;
    return Objects.equals(this.coin, sapiV1CapitalDepositAddressListGet200ResponseInner.coin) &&
        Objects.equals(this.address, sapiV1CapitalDepositAddressListGet200ResponseInner.address) &&
        Objects.equals(this.isDefault, sapiV1CapitalDepositAddressListGet200ResponseInner.isDefault);
  }

  @Override
  public int hashCode() {
    return Objects.hash(coin, address, isDefault);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SapiV1CapitalDepositAddressListGet200ResponseInner {\n");
    sb.append("    coin: ").append(toIndentedString(coin)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    isDefault: ").append(toIndentedString(isDefault)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

