/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SapiV1SimpleEarnLockedHistoryRewardsRecordGet200ResponseRowsInner
 */
@JsonPropertyOrder({
  SapiV1SimpleEarnLockedHistoryRewardsRecordGet200ResponseRowsInner.JSON_PROPERTY_POSITION_ID,
  SapiV1SimpleEarnLockedHistoryRewardsRecordGet200ResponseRowsInner.JSON_PROPERTY_TIME,
  SapiV1SimpleEarnLockedHistoryRewardsRecordGet200ResponseRowsInner.JSON_PROPERTY_ASSET,
  SapiV1SimpleEarnLockedHistoryRewardsRecordGet200ResponseRowsInner.JSON_PROPERTY_LOCK_PERIOD,
  SapiV1SimpleEarnLockedHistoryRewardsRecordGet200ResponseRowsInner.JSON_PROPERTY_AMOUNT
})
@JsonTypeName("_sapi_v1_simple_earn_locked_history_rewardsRecord_get_200_response_rows_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SapiV1SimpleEarnLockedHistoryRewardsRecordGet200ResponseRowsInner {
  public static final String JSON_PROPERTY_POSITION_ID = "positionId";
  private String positionId;

  public static final String JSON_PROPERTY_TIME = "time";
  private Long time;

  public static final String JSON_PROPERTY_ASSET = "asset";
  private String asset;

  public static final String JSON_PROPERTY_LOCK_PERIOD = "lockPeriod";
  private String lockPeriod;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private String amount;

  public SapiV1SimpleEarnLockedHistoryRewardsRecordGet200ResponseRowsInner() {
  }

  public SapiV1SimpleEarnLockedHistoryRewardsRecordGet200ResponseRowsInner positionId(String positionId) {
    
    this.positionId = positionId;
    return this;
  }

   /**
   * Get positionId
   * @return positionId
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "123123", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_POSITION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPositionId() {
    return positionId;
  }


  @JsonProperty(JSON_PROPERTY_POSITION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPositionId(String positionId) {
    this.positionId = positionId;
  }


  public SapiV1SimpleEarnLockedHistoryRewardsRecordGet200ResponseRowsInner time(Long time) {
    
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1577257222000", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getTime() {
    return time;
  }


  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTime(Long time) {
    this.time = time;
  }


  public SapiV1SimpleEarnLockedHistoryRewardsRecordGet200ResponseRowsInner asset(String asset) {
    
    this.asset = asset;
    return this;
  }

   /**
   * Get asset
   * @return asset
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "BNB", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ASSET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAsset() {
    return asset;
  }


  @JsonProperty(JSON_PROPERTY_ASSET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAsset(String asset) {
    this.asset = asset;
  }


  public SapiV1SimpleEarnLockedHistoryRewardsRecordGet200ResponseRowsInner lockPeriod(String lockPeriod) {
    
    this.lockPeriod = lockPeriod;
    return this;
  }

   /**
   * Get lockPeriod
   * @return lockPeriod
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "30", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LOCK_PERIOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLockPeriod() {
    return lockPeriod;
  }


  @JsonProperty(JSON_PROPERTY_LOCK_PERIOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLockPeriod(String lockPeriod) {
    this.lockPeriod = lockPeriod;
  }


  public SapiV1SimpleEarnLockedHistoryRewardsRecordGet200ResponseRowsInner amount(String amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "21312.23223", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(String amount) {
    this.amount = amount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SapiV1SimpleEarnLockedHistoryRewardsRecordGet200ResponseRowsInner sapiV1SimpleEarnLockedHistoryRewardsRecordGet200ResponseRowsInner = (SapiV1SimpleEarnLockedHistoryRewardsRecordGet200ResponseRowsInner) o;
    return Objects.equals(this.positionId, sapiV1SimpleEarnLockedHistoryRewardsRecordGet200ResponseRowsInner.positionId) &&
        Objects.equals(this.time, sapiV1SimpleEarnLockedHistoryRewardsRecordGet200ResponseRowsInner.time) &&
        Objects.equals(this.asset, sapiV1SimpleEarnLockedHistoryRewardsRecordGet200ResponseRowsInner.asset) &&
        Objects.equals(this.lockPeriod, sapiV1SimpleEarnLockedHistoryRewardsRecordGet200ResponseRowsInner.lockPeriod) &&
        Objects.equals(this.amount, sapiV1SimpleEarnLockedHistoryRewardsRecordGet200ResponseRowsInner.amount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(positionId, time, asset, lockPeriod, amount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SapiV1SimpleEarnLockedHistoryRewardsRecordGet200ResponseRowsInner {\n");
    sb.append("    positionId: ").append(toIndentedString(positionId)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    asset: ").append(toIndentedString(asset)).append("\n");
    sb.append("    lockPeriod: ").append(toIndentedString(lockPeriod)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

