/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner
 */
@JsonPropertyOrder({
  SapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner.JSON_PROPERTY_LOAN_COIN,
  SapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner.JSON_PROPERTY_COLLATERAL_COIN,
  SapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner.JSON_PROPERTY_DIRECTION,
  SapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner.JSON_PROPERTY_COLLATERAL_AMOUNT,
  SapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner.JSON_PROPERTY_PRE_L_T_V,
  SapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner.JSON_PROPERTY_AFTER_L_T_V,
  SapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner.JSON_PROPERTY_ADJUST_TIME
})
@JsonTypeName("_sapi_v2_loan_flexible_ltv_adjustment_history_get_200_response_rows_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner {
  public static final String JSON_PROPERTY_LOAN_COIN = "loanCoin";
  private String loanCoin;

  public static final String JSON_PROPERTY_COLLATERAL_COIN = "collateralCoin";
  private String collateralCoin;

  public static final String JSON_PROPERTY_DIRECTION = "direction";
  private String direction;

  public static final String JSON_PROPERTY_COLLATERAL_AMOUNT = "collateralAmount";
  private String collateralAmount;

  public static final String JSON_PROPERTY_PRE_L_T_V = "preLTV";
  private String preLTV;

  public static final String JSON_PROPERTY_AFTER_L_T_V = "afterLTV";
  private String afterLTV;

  public static final String JSON_PROPERTY_ADJUST_TIME = "adjustTime";
  private Long adjustTime;

  public SapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner() {
  }

  public SapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner loanCoin(String loanCoin) {
    
    this.loanCoin = loanCoin;
    return this;
  }

   /**
   * Get loanCoin
   * @return loanCoin
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "BNB", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LOAN_COIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLoanCoin() {
    return loanCoin;
  }


  @JsonProperty(JSON_PROPERTY_LOAN_COIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLoanCoin(String loanCoin) {
    this.loanCoin = loanCoin;
  }


  public SapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner collateralCoin(String collateralCoin) {
    
    this.collateralCoin = collateralCoin;
    return this;
  }

   /**
   * Get collateralCoin
   * @return collateralCoin
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "BNB", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_COLLATERAL_COIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCollateralCoin() {
    return collateralCoin;
  }


  @JsonProperty(JSON_PROPERTY_COLLATERAL_COIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCollateralCoin(String collateralCoin) {
    this.collateralCoin = collateralCoin;
  }


  public SapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner direction(String direction) {
    
    this.direction = direction;
    return this;
  }

   /**
   * Get direction
   * @return direction
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "ADDITIONAL", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DIRECTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDirection() {
    return direction;
  }


  @JsonProperty(JSON_PROPERTY_DIRECTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDirection(String direction) {
    this.direction = direction;
  }


  public SapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner collateralAmount(String collateralAmount) {
    
    this.collateralAmount = collateralAmount;
    return this;
  }

   /**
   * Get collateralAmount
   * @return collateralAmount
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "5.75", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_COLLATERAL_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCollateralAmount() {
    return collateralAmount;
  }


  @JsonProperty(JSON_PROPERTY_COLLATERAL_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCollateralAmount(String collateralAmount) {
    this.collateralAmount = collateralAmount;
  }


  public SapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner preLTV(String preLTV) {
    
    this.preLTV = preLTV;
    return this;
  }

   /**
   * Get preLTV
   * @return preLTV
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.83", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PRE_L_T_V)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPreLTV() {
    return preLTV;
  }


  @JsonProperty(JSON_PROPERTY_PRE_L_T_V)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPreLTV(String preLTV) {
    this.preLTV = preLTV;
  }


  public SapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner afterLTV(String afterLTV) {
    
    this.afterLTV = afterLTV;
    return this;
  }

   /**
   * Get afterLTV
   * @return afterLTV
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.5", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_AFTER_L_T_V)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAfterLTV() {
    return afterLTV;
  }


  @JsonProperty(JSON_PROPERTY_AFTER_L_T_V)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAfterLTV(String afterLTV) {
    this.afterLTV = afterLTV;
  }


  public SapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner adjustTime(Long adjustTime) {
    
    this.adjustTime = adjustTime;
    return this;
  }

   /**
   * Get adjustTime
   * @return adjustTime
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1575018510000", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ADJUST_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getAdjustTime() {
    return adjustTime;
  }


  @JsonProperty(JSON_PROPERTY_ADJUST_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAdjustTime(Long adjustTime) {
    this.adjustTime = adjustTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner sapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner = (SapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner) o;
    return Objects.equals(this.loanCoin, sapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner.loanCoin) &&
        Objects.equals(this.collateralCoin, sapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner.collateralCoin) &&
        Objects.equals(this.direction, sapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner.direction) &&
        Objects.equals(this.collateralAmount, sapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner.collateralAmount) &&
        Objects.equals(this.preLTV, sapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner.preLTV) &&
        Objects.equals(this.afterLTV, sapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner.afterLTV) &&
        Objects.equals(this.adjustTime, sapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner.adjustTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loanCoin, collateralCoin, direction, collateralAmount, preLTV, afterLTV, adjustTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SapiV2LoanFlexibleLtvAdjustmentHistoryGet200ResponseRowsInner {\n");
    sb.append("    loanCoin: ").append(toIndentedString(loanCoin)).append("\n");
    sb.append("    collateralCoin: ").append(toIndentedString(collateralCoin)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    collateralAmount: ").append(toIndentedString(collateralAmount)).append("\n");
    sb.append("    preLTV: ").append(toIndentedString(preLTV)).append("\n");
    sb.append("    afterLTV: ").append(toIndentedString(afterLTV)).append("\n");
    sb.append("    adjustTime: ").append(toIndentedString(adjustTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

