/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner
 */
@JsonPropertyOrder({
  SapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner.JSON_PROPERTY_CREATE_TIME,
  SapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner.JSON_PROPERTY_TRAN_ID,
  SapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner.JSON_PROPERTY_TYPE,
  SapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner.JSON_PROPERTY_ASSET,
  SapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner.JSON_PROPERTY_AMOUNT,
  SapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner.JSON_PROPERTY_STATUS
})
@JsonTypeName("_sapi_v1_asset_ledger_transfer_cloud_mining_queryByPage_get_200_response_rows_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner {
  public static final String JSON_PROPERTY_CREATE_TIME = "createTime";
  private Long createTime;

  public static final String JSON_PROPERTY_TRAN_ID = "tranId";
  private Long tranId;

  public static final String JSON_PROPERTY_TYPE = "type";
  private Long type;

  public static final String JSON_PROPERTY_ASSET = "asset";
  private String asset;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private String amount;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public SapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner() {
  }

  public SapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner createTime(Long createTime) {
    
    this.createTime = createTime;
    return this;
  }

   /**
   * Get createTime
   * @return createTime
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1667880112000", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CREATE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getCreateTime() {
    return createTime;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreateTime(Long createTime) {
    this.createTime = createTime;
  }


  public SapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner tranId(Long tranId) {
    
    this.tranId = tranId;
    return this;
  }

   /**
   * Get tranId
   * @return tranId
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "121230610120", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TRAN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getTranId() {
    return tranId;
  }


  @JsonProperty(JSON_PROPERTY_TRAN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTranId(Long tranId) {
    this.tranId = tranId;
  }


  public SapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner type(Long type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "248", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(Long type) {
    this.type = type;
  }


  public SapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner asset(String asset) {
    
    this.asset = asset;
    return this;
  }

   /**
   * Get asset
   * @return asset
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "USDT", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ASSET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAsset() {
    return asset;
  }


  @JsonProperty(JSON_PROPERTY_ASSET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAsset(String asset) {
    this.asset = asset;
  }


  public SapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner amount(String amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(String amount) {
    this.amount = amount;
  }


  public SapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "S", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner sapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner = (SapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner) o;
    return Objects.equals(this.createTime, sapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner.createTime) &&
        Objects.equals(this.tranId, sapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner.tranId) &&
        Objects.equals(this.type, sapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner.type) &&
        Objects.equals(this.asset, sapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner.asset) &&
        Objects.equals(this.amount, sapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner.amount) &&
        Objects.equals(this.status, sapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createTime, tranId, type, asset, amount, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SapiV1AssetLedgerTransferCloudMiningQueryByPageGet200ResponseRowsInner {\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    tranId: ").append(toIndentedString(tranId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    asset: ").append(toIndentedString(asset)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

