/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.olbaid.binance.service.model.SapiV1CapitalConfigGetallGet200ResponseInnerNetworkListInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SapiV1CapitalConfigGetallGet200ResponseInner
 */
@JsonPropertyOrder({
  SapiV1CapitalConfigGetallGet200ResponseInner.JSON_PROPERTY_COIN,
  SapiV1CapitalConfigGetallGet200ResponseInner.JSON_PROPERTY_DEPOSIT_ALL_ENABLE,
  SapiV1CapitalConfigGetallGet200ResponseInner.JSON_PROPERTY_FREE,
  SapiV1CapitalConfigGetallGet200ResponseInner.JSON_PROPERTY_FREEZE,
  SapiV1CapitalConfigGetallGet200ResponseInner.JSON_PROPERTY_IPOABLE,
  SapiV1CapitalConfigGetallGet200ResponseInner.JSON_PROPERTY_IPOING,
  SapiV1CapitalConfigGetallGet200ResponseInner.JSON_PROPERTY_IS_LEGAL_MONEY,
  SapiV1CapitalConfigGetallGet200ResponseInner.JSON_PROPERTY_LOCKED,
  SapiV1CapitalConfigGetallGet200ResponseInner.JSON_PROPERTY_NAME,
  SapiV1CapitalConfigGetallGet200ResponseInner.JSON_PROPERTY_NETWORK_LIST,
  SapiV1CapitalConfigGetallGet200ResponseInner.JSON_PROPERTY_STORAGE,
  SapiV1CapitalConfigGetallGet200ResponseInner.JSON_PROPERTY_TRADING,
  SapiV1CapitalConfigGetallGet200ResponseInner.JSON_PROPERTY_WITHDRAW_ALL_ENABLE,
  SapiV1CapitalConfigGetallGet200ResponseInner.JSON_PROPERTY_WITHDRAWING
})
@JsonTypeName("_sapi_v1_capital_config_getall_get_200_response_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SapiV1CapitalConfigGetallGet200ResponseInner {
  public static final String JSON_PROPERTY_COIN = "coin";
  private String coin;

  public static final String JSON_PROPERTY_DEPOSIT_ALL_ENABLE = "depositAllEnable";
  private Boolean depositAllEnable;

  public static final String JSON_PROPERTY_FREE = "free";
  private String free;

  public static final String JSON_PROPERTY_FREEZE = "freeze";
  private String freeze;

  public static final String JSON_PROPERTY_IPOABLE = "ipoable";
  private String ipoable;

  public static final String JSON_PROPERTY_IPOING = "ipoing";
  private String ipoing;

  public static final String JSON_PROPERTY_IS_LEGAL_MONEY = "isLegalMoney";
  private Boolean isLegalMoney;

  public static final String JSON_PROPERTY_LOCKED = "locked";
  private String locked;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_NETWORK_LIST = "networkList";
  private List<SapiV1CapitalConfigGetallGet200ResponseInnerNetworkListInner> networkList = new ArrayList<>();

  public static final String JSON_PROPERTY_STORAGE = "storage";
  private String storage;

  public static final String JSON_PROPERTY_TRADING = "trading";
  private Boolean trading;

  public static final String JSON_PROPERTY_WITHDRAW_ALL_ENABLE = "withdrawAllEnable";
  private Boolean withdrawAllEnable;

  public static final String JSON_PROPERTY_WITHDRAWING = "withdrawing";
  private String withdrawing;

  public SapiV1CapitalConfigGetallGet200ResponseInner() {
  }

  public SapiV1CapitalConfigGetallGet200ResponseInner coin(String coin) {
    
    this.coin = coin;
    return this;
  }

   /**
   * Get coin
   * @return coin
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "BTC", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_COIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCoin() {
    return coin;
  }


  @JsonProperty(JSON_PROPERTY_COIN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCoin(String coin) {
    this.coin = coin;
  }


  public SapiV1CapitalConfigGetallGet200ResponseInner depositAllEnable(Boolean depositAllEnable) {
    
    this.depositAllEnable = depositAllEnable;
    return this;
  }

   /**
   * Get depositAllEnable
   * @return depositAllEnable
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DEPOSIT_ALL_ENABLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getDepositAllEnable() {
    return depositAllEnable;
  }


  @JsonProperty(JSON_PROPERTY_DEPOSIT_ALL_ENABLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDepositAllEnable(Boolean depositAllEnable) {
    this.depositAllEnable = depositAllEnable;
  }


  public SapiV1CapitalConfigGetallGet200ResponseInner free(String free) {
    
    this.free = free;
    return this;
  }

   /**
   * Get free
   * @return free
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.00000000", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_FREE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFree() {
    return free;
  }


  @JsonProperty(JSON_PROPERTY_FREE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFree(String free) {
    this.free = free;
  }


  public SapiV1CapitalConfigGetallGet200ResponseInner freeze(String freeze) {
    
    this.freeze = freeze;
    return this;
  }

   /**
   * Get freeze
   * @return freeze
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.00000000", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_FREEZE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFreeze() {
    return freeze;
  }


  @JsonProperty(JSON_PROPERTY_FREEZE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFreeze(String freeze) {
    this.freeze = freeze;
  }


  public SapiV1CapitalConfigGetallGet200ResponseInner ipoable(String ipoable) {
    
    this.ipoable = ipoable;
    return this;
  }

   /**
   * Get ipoable
   * @return ipoable
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.00000000", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_IPOABLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIpoable() {
    return ipoable;
  }


  @JsonProperty(JSON_PROPERTY_IPOABLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIpoable(String ipoable) {
    this.ipoable = ipoable;
  }


  public SapiV1CapitalConfigGetallGet200ResponseInner ipoing(String ipoing) {
    
    this.ipoing = ipoing;
    return this;
  }

   /**
   * Get ipoing
   * @return ipoing
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.00000000", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_IPOING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIpoing() {
    return ipoing;
  }


  @JsonProperty(JSON_PROPERTY_IPOING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIpoing(String ipoing) {
    this.ipoing = ipoing;
  }


  public SapiV1CapitalConfigGetallGet200ResponseInner isLegalMoney(Boolean isLegalMoney) {
    
    this.isLegalMoney = isLegalMoney;
    return this;
  }

   /**
   * Get isLegalMoney
   * @return isLegalMoney
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "false", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_IS_LEGAL_MONEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsLegalMoney() {
    return isLegalMoney;
  }


  @JsonProperty(JSON_PROPERTY_IS_LEGAL_MONEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsLegalMoney(Boolean isLegalMoney) {
    this.isLegalMoney = isLegalMoney;
  }


  public SapiV1CapitalConfigGetallGet200ResponseInner locked(String locked) {
    
    this.locked = locked;
    return this;
  }

   /**
   * Get locked
   * @return locked
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.00000000", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LOCKED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLocked() {
    return locked;
  }


  @JsonProperty(JSON_PROPERTY_LOCKED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLocked(String locked) {
    this.locked = locked;
  }


  public SapiV1CapitalConfigGetallGet200ResponseInner name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "Bitcoin", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public SapiV1CapitalConfigGetallGet200ResponseInner networkList(List<SapiV1CapitalConfigGetallGet200ResponseInnerNetworkListInner> networkList) {
    
    this.networkList = networkList;
    return this;
  }

  public SapiV1CapitalConfigGetallGet200ResponseInner addNetworkListItem(SapiV1CapitalConfigGetallGet200ResponseInnerNetworkListInner networkListItem) {
    this.networkList.add(networkListItem);
    return this;
  }

   /**
   * Get networkList
   * @return networkList
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_NETWORK_LIST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<SapiV1CapitalConfigGetallGet200ResponseInnerNetworkListInner> getNetworkList() {
    return networkList;
  }


  @JsonProperty(JSON_PROPERTY_NETWORK_LIST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNetworkList(List<SapiV1CapitalConfigGetallGet200ResponseInnerNetworkListInner> networkList) {
    this.networkList = networkList;
  }


  public SapiV1CapitalConfigGetallGet200ResponseInner storage(String storage) {
    
    this.storage = storage;
    return this;
  }

   /**
   * Get storage
   * @return storage
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.00000000", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_STORAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStorage() {
    return storage;
  }


  @JsonProperty(JSON_PROPERTY_STORAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStorage(String storage) {
    this.storage = storage;
  }


  public SapiV1CapitalConfigGetallGet200ResponseInner trading(Boolean trading) {
    
    this.trading = trading;
    return this;
  }

   /**
   * Get trading
   * @return trading
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TRADING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getTrading() {
    return trading;
  }


  @JsonProperty(JSON_PROPERTY_TRADING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTrading(Boolean trading) {
    this.trading = trading;
  }


  public SapiV1CapitalConfigGetallGet200ResponseInner withdrawAllEnable(Boolean withdrawAllEnable) {
    
    this.withdrawAllEnable = withdrawAllEnable;
    return this;
  }

   /**
   * Get withdrawAllEnable
   * @return withdrawAllEnable
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_WITHDRAW_ALL_ENABLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getWithdrawAllEnable() {
    return withdrawAllEnable;
  }


  @JsonProperty(JSON_PROPERTY_WITHDRAW_ALL_ENABLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWithdrawAllEnable(Boolean withdrawAllEnable) {
    this.withdrawAllEnable = withdrawAllEnable;
  }


  public SapiV1CapitalConfigGetallGet200ResponseInner withdrawing(String withdrawing) {
    
    this.withdrawing = withdrawing;
    return this;
  }

   /**
   * Get withdrawing
   * @return withdrawing
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "0.00000000", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_WITHDRAWING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getWithdrawing() {
    return withdrawing;
  }


  @JsonProperty(JSON_PROPERTY_WITHDRAWING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWithdrawing(String withdrawing) {
    this.withdrawing = withdrawing;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SapiV1CapitalConfigGetallGet200ResponseInner sapiV1CapitalConfigGetallGet200ResponseInner = (SapiV1CapitalConfigGetallGet200ResponseInner) o;
    return Objects.equals(this.coin, sapiV1CapitalConfigGetallGet200ResponseInner.coin) &&
        Objects.equals(this.depositAllEnable, sapiV1CapitalConfigGetallGet200ResponseInner.depositAllEnable) &&
        Objects.equals(this.free, sapiV1CapitalConfigGetallGet200ResponseInner.free) &&
        Objects.equals(this.freeze, sapiV1CapitalConfigGetallGet200ResponseInner.freeze) &&
        Objects.equals(this.ipoable, sapiV1CapitalConfigGetallGet200ResponseInner.ipoable) &&
        Objects.equals(this.ipoing, sapiV1CapitalConfigGetallGet200ResponseInner.ipoing) &&
        Objects.equals(this.isLegalMoney, sapiV1CapitalConfigGetallGet200ResponseInner.isLegalMoney) &&
        Objects.equals(this.locked, sapiV1CapitalConfigGetallGet200ResponseInner.locked) &&
        Objects.equals(this.name, sapiV1CapitalConfigGetallGet200ResponseInner.name) &&
        Objects.equals(this.networkList, sapiV1CapitalConfigGetallGet200ResponseInner.networkList) &&
        Objects.equals(this.storage, sapiV1CapitalConfigGetallGet200ResponseInner.storage) &&
        Objects.equals(this.trading, sapiV1CapitalConfigGetallGet200ResponseInner.trading) &&
        Objects.equals(this.withdrawAllEnable, sapiV1CapitalConfigGetallGet200ResponseInner.withdrawAllEnable) &&
        Objects.equals(this.withdrawing, sapiV1CapitalConfigGetallGet200ResponseInner.withdrawing);
  }

  @Override
  public int hashCode() {
    return Objects.hash(coin, depositAllEnable, free, freeze, ipoable, ipoing, isLegalMoney, locked, name, networkList, storage, trading, withdrawAllEnable, withdrawing);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SapiV1CapitalConfigGetallGet200ResponseInner {\n");
    sb.append("    coin: ").append(toIndentedString(coin)).append("\n");
    sb.append("    depositAllEnable: ").append(toIndentedString(depositAllEnable)).append("\n");
    sb.append("    free: ").append(toIndentedString(free)).append("\n");
    sb.append("    freeze: ").append(toIndentedString(freeze)).append("\n");
    sb.append("    ipoable: ").append(toIndentedString(ipoable)).append("\n");
    sb.append("    ipoing: ").append(toIndentedString(ipoing)).append("\n");
    sb.append("    isLegalMoney: ").append(toIndentedString(isLegalMoney)).append("\n");
    sb.append("    locked: ").append(toIndentedString(locked)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    networkList: ").append(toIndentedString(networkList)).append("\n");
    sb.append("    storage: ").append(toIndentedString(storage)).append("\n");
    sb.append("    trading: ").append(toIndentedString(trading)).append("\n");
    sb.append("    withdrawAllEnable: ").append(toIndentedString(withdrawAllEnable)).append("\n");
    sb.append("    withdrawing: ").append(toIndentedString(withdrawing)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

