/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner
 */
@JsonPropertyOrder({
  SapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner.JSON_PROPERTY_CONFIG_ID,
  SapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner.JSON_PROPERTY_POOL_USERNAME,
  SapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner.JSON_PROPERTY_TO_POOL_USERNAME,
  SapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner.JSON_PROPERTY_ALGO_NAME,
  SapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner.JSON_PROPERTY_HASH_RATE,
  SapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner.JSON_PROPERTY_START_DAY,
  SapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner.JSON_PROPERTY_END_DAY,
  SapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner.JSON_PROPERTY_STATUS
})
@JsonTypeName("_sapi_v1_mining_hash_transfer_config_details_list_get_200_response_data_configDetails_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner {
  public static final String JSON_PROPERTY_CONFIG_ID = "configId";
  private Long configId;

  public static final String JSON_PROPERTY_POOL_USERNAME = "poolUsername";
  private String poolUsername;

  public static final String JSON_PROPERTY_TO_POOL_USERNAME = "toPoolUsername";
  private String toPoolUsername;

  public static final String JSON_PROPERTY_ALGO_NAME = "algoName";
  private String algoName;

  public static final String JSON_PROPERTY_HASH_RATE = "hashRate";
  private Long hashRate;

  public static final String JSON_PROPERTY_START_DAY = "startDay";
  private Long startDay;

  public static final String JSON_PROPERTY_END_DAY = "endDay";
  private Long endDay;

  public static final String JSON_PROPERTY_STATUS = "status";
  private Integer status;

  public SapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner() {
  }

  public SapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner configId(Long configId) {
    
    this.configId = configId;
    return this;
  }

   /**
   * Mining ID
   * @return configId
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "168", required = true, value = "Mining ID")
  @JsonProperty(JSON_PROPERTY_CONFIG_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getConfigId() {
    return configId;
  }


  @JsonProperty(JSON_PROPERTY_CONFIG_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConfigId(Long configId) {
    this.configId = configId;
  }


  public SapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner poolUsername(String poolUsername) {
    
    this.poolUsername = poolUsername;
    return this;
  }

   /**
   * Transfer out of subaccount
   * @return poolUsername
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "123", required = true, value = "Transfer out of subaccount")
  @JsonProperty(JSON_PROPERTY_POOL_USERNAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPoolUsername() {
    return poolUsername;
  }


  @JsonProperty(JSON_PROPERTY_POOL_USERNAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPoolUsername(String poolUsername) {
    this.poolUsername = poolUsername;
  }


  public SapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner toPoolUsername(String toPoolUsername) {
    
    this.toPoolUsername = toPoolUsername;
    return this;
  }

   /**
   * Transfer into subaccount
   * @return toPoolUsername
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "user1", required = true, value = "Transfer into subaccount")
  @JsonProperty(JSON_PROPERTY_TO_POOL_USERNAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getToPoolUsername() {
    return toPoolUsername;
  }


  @JsonProperty(JSON_PROPERTY_TO_POOL_USERNAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToPoolUsername(String toPoolUsername) {
    this.toPoolUsername = toPoolUsername;
  }


  public SapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner algoName(String algoName) {
    
    this.algoName = algoName;
    return this;
  }

   /**
   * Transfer algorithm
   * @return algoName
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "Ethash", required = true, value = "Transfer algorithm")
  @JsonProperty(JSON_PROPERTY_ALGO_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAlgoName() {
    return algoName;
  }


  @JsonProperty(JSON_PROPERTY_ALGO_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAlgoName(String algoName) {
    this.algoName = algoName;
  }


  public SapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner hashRate(Long hashRate) {
    
    this.hashRate = hashRate;
    return this;
  }

   /**
   * Transferred Hashrate quantity
   * @return hashRate
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "5000000", required = true, value = "Transferred Hashrate quantity")
  @JsonProperty(JSON_PROPERTY_HASH_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getHashRate() {
    return hashRate;
  }


  @JsonProperty(JSON_PROPERTY_HASH_RATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHashRate(Long hashRate) {
    this.hashRate = hashRate;
  }


  public SapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner startDay(Long startDay) {
    
    this.startDay = startDay;
    return this;
  }

   /**
   * Start date
   * @return startDay
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "20201210", required = true, value = "Start date")
  @JsonProperty(JSON_PROPERTY_START_DAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getStartDay() {
    return startDay;
  }


  @JsonProperty(JSON_PROPERTY_START_DAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStartDay(Long startDay) {
    this.startDay = startDay;
  }


  public SapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner endDay(Long endDay) {
    
    this.endDay = endDay;
    return this;
  }

   /**
   * End date
   * @return endDay
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "20210405", required = true, value = "End date")
  @JsonProperty(JSON_PROPERTY_END_DAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getEndDay() {
    return endDay;
  }


  @JsonProperty(JSON_PROPERTY_END_DAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEndDay(Long endDay) {
    this.endDay = endDay;
  }


  public SapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner status(Integer status) {
    
    this.status = status;
    return this;
  }

   /**
   * 0 Processing, 1ï¼šCancelled, 2ï¼šTerminated 
   * @return status
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "0 Processing, 1ï¼šCancelled, 2ï¼šTerminated ")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(Integer status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner sapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner = (SapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner) o;
    return Objects.equals(this.configId, sapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner.configId) &&
        Objects.equals(this.poolUsername, sapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner.poolUsername) &&
        Objects.equals(this.toPoolUsername, sapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner.toPoolUsername) &&
        Objects.equals(this.algoName, sapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner.algoName) &&
        Objects.equals(this.hashRate, sapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner.hashRate) &&
        Objects.equals(this.startDay, sapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner.startDay) &&
        Objects.equals(this.endDay, sapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner.endDay) &&
        Objects.equals(this.status, sapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(configId, poolUsername, toPoolUsername, algoName, hashRate, startDay, endDay, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SapiV1MiningHashTransferConfigDetailsListGet200ResponseDataConfigDetailsInner {\n");
    sb.append("    configId: ").append(toIndentedString(configId)).append("\n");
    sb.append("    poolUsername: ").append(toIndentedString(poolUsername)).append("\n");
    sb.append("    toPoolUsername: ").append(toIndentedString(toPoolUsername)).append("\n");
    sb.append("    algoName: ").append(toIndentedString(algoName)).append("\n");
    sb.append("    hashRate: ").append(toIndentedString(hashRate)).append("\n");
    sb.append("    startDay: ").append(toIndentedString(startDay)).append("\n");
    sb.append("    endDay: ").append(toIndentedString(endDay)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

