/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.olbaid.binance.service.model.SubAccountUSDTFuturesSummaryFutureAccountSummaryResp;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SubAccountUSDTFuturesSummary
 */
@JsonPropertyOrder({
  SubAccountUSDTFuturesSummary.JSON_PROPERTY_FUTURE_ACCOUNT_SUMMARY_RESP
})
@JsonTypeName("subAccountUSDTFuturesSummary")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SubAccountUSDTFuturesSummary {
  public static final String JSON_PROPERTY_FUTURE_ACCOUNT_SUMMARY_RESP = "futureAccountSummaryResp";
  private SubAccountUSDTFuturesSummaryFutureAccountSummaryResp futureAccountSummaryResp;

  public SubAccountUSDTFuturesSummary() {
  }

  public SubAccountUSDTFuturesSummary futureAccountSummaryResp(SubAccountUSDTFuturesSummaryFutureAccountSummaryResp futureAccountSummaryResp) {
    
    this.futureAccountSummaryResp = futureAccountSummaryResp;
    return this;
  }

   /**
   * Get futureAccountSummaryResp
   * @return futureAccountSummaryResp
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_FUTURE_ACCOUNT_SUMMARY_RESP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SubAccountUSDTFuturesSummaryFutureAccountSummaryResp getFutureAccountSummaryResp() {
    return futureAccountSummaryResp;
  }


  @JsonProperty(JSON_PROPERTY_FUTURE_ACCOUNT_SUMMARY_RESP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFutureAccountSummaryResp(SubAccountUSDTFuturesSummaryFutureAccountSummaryResp futureAccountSummaryResp) {
    this.futureAccountSummaryResp = futureAccountSummaryResp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubAccountUSDTFuturesSummary subAccountUSDTFuturesSummary = (SubAccountUSDTFuturesSummary) o;
    return Objects.equals(this.futureAccountSummaryResp, subAccountUSDTFuturesSummary.futureAccountSummaryResp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(futureAccountSummaryResp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubAccountUSDTFuturesSummary {\n");
    sb.append("    futureAccountSummaryResp: ").append(toIndentedString(futureAccountSummaryResp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

