/*
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.olbaid.binance.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.olbaid.binance.service.model.SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVosInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SubAccountCOINFuturesPositionRisk
 */
@JsonPropertyOrder({
  SubAccountCOINFuturesPositionRisk.JSON_PROPERTY_DELIVERY_POSITION_RISK_VOS
})
@JsonTypeName("subAccountCOINFuturesPositionRisk")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SubAccountCOINFuturesPositionRisk {
  public static final String JSON_PROPERTY_DELIVERY_POSITION_RISK_VOS = "deliveryPositionRiskVos";
  private List<SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVosInner> deliveryPositionRiskVos = new ArrayList<>();

  public SubAccountCOINFuturesPositionRisk() {
  }

  public SubAccountCOINFuturesPositionRisk deliveryPositionRiskVos(List<SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVosInner> deliveryPositionRiskVos) {
    
    this.deliveryPositionRiskVos = deliveryPositionRiskVos;
    return this;
  }

  public SubAccountCOINFuturesPositionRisk addDeliveryPositionRiskVosItem(SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVosInner deliveryPositionRiskVosItem) {
    this.deliveryPositionRiskVos.add(deliveryPositionRiskVosItem);
    return this;
  }

   /**
   * Get deliveryPositionRiskVos
   * @return deliveryPositionRiskVos
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DELIVERY_POSITION_RISK_VOS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVosInner> getDeliveryPositionRiskVos() {
    return deliveryPositionRiskVos;
  }


  @JsonProperty(JSON_PROPERTY_DELIVERY_POSITION_RISK_VOS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDeliveryPositionRiskVos(List<SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVosInner> deliveryPositionRiskVos) {
    this.deliveryPositionRiskVos = deliveryPositionRiskVos;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubAccountCOINFuturesPositionRisk subAccountCOINFuturesPositionRisk = (SubAccountCOINFuturesPositionRisk) o;
    return Objects.equals(this.deliveryPositionRiskVos, subAccountCOINFuturesPositionRisk.deliveryPositionRiskVos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deliveryPositionRiskVos);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubAccountCOINFuturesPositionRisk {\n");
    sb.append("    deliveryPositionRiskVos: ").append(toIndentedString(deliveryPositionRiskVos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

